Repository 0xPolygon/polygon-edge, pull requests merged in 2022-09, with the labels that each got.

#712 Added EdgeNet CD pipeline
  .github/workflows/ansible/update_edgenet.yaml
  .github/workflows/deploy_edgenet.yaml
Labels: feature

#710 [FIX] Properly handle block-gas-target flag
  command/server/init.go
Labels: bug fix

#716 [Rootchain Staking] Add rootchain config command
  .gitignore
  command/helper/helper.go
  command/root/root.go
  command/rootchain/params.go
  command/rootchain/result.go
  command/rootchain/rootchain.go
  rootchain/config.go
  rootchain/config_test.go
Labels: feature

#688 [Feature] Added more information to the version command
  Makefile
  command/version/result.go
  command/version/version.go
  versioning/versioning.go
Labels: feature

#741 [Memory fix] Remove memory leak in event subscriptions
  blockchain/subscription.go
  blockchain/subscription_test.go
Labels: hotfix

#719 Fix zero from field in Tx
  blockchain/blockchain.go
  blockchain/blockchain_test.go
  blockchain/testing.go
  e2e/framework/testserver.go
  e2e/transaction_test.go
  server/server.go
Labels: bug fix

#723 Remove io/ioutil package due to deprecation
  blockchain/storage/leveldb/leveldb_test.go
  chain/chain.go
  chain/chain_bindata.go
  chain/chain_test.go
  command/common.go
  command/helper/helper.go
  command/loadbot/generator/generator.go
  command/server/config/config.go
  consensus/ibft/fork/helper.go
  consensus/ibft/fork/helper_test.go
  consensus/ibft/fork/storewrapper_test.go
  e2e/framework/helper.go
  helper/keystore/keystore.go
  jsonrpc/jsonrpc.go
  network/e2e_testing.go
  secrets/config.go
  secrets/local/local.go
  secrets/local/local_test.go
  state/runtime/precompiled/testing.go
  tests/evm_test.go
  tests/state_test.go
  tests/testing.go
Labels: bug fix

#742 Cleanup inactive transactions in non-validator
  command/server/init.go
  consensus/consensus.go
  consensus/dev/dev.go
  consensus/dummy/dummy.go
  consensus/ibft/ibft.go
  consensus/ibft/transport.go
  e2e/broadcast_test.go
  e2e/framework/config.go
  e2e/framework/testserver.go
  e2e/ibft_test.go
  e2e/pos_poa_switch_test.go
  e2e/pos_test.go
  e2e/syncer_test.go
  e2e/transaction_test.go
  e2e/txpool_test.go
  e2e/websocket_test.go
  server/server.go
  txpool/account.go
  txpool/txpool.go
  txpool/txpool_test.go
Labels: bug fix

#739 [TxPool] Fix double nonce in promoted
  txpool/account.go
  txpool/queue.go
  txpool/txpool.go
  txpool/txpool_test.go
Labels: bug fix

#747 Added docker setup for local env
  .dockerignore
  Makefile
  docker/local/Dockerfile
  docker/local/docker-compose.yml
  docker/local/polygon-edge.sh
Labels: feature

#717 [Rootnet Staking] SAMUEL
  blockchain/storage/keyvalue.go
  blockchain/storage/storage.go
  blockchain/storage/testing.go
  command/rootchain/params.go
  command/rootchain/rootchain.go
  rootchain/config.go
  rootchain/config_test.go
  rootchain/event.go
  rootchain/event_test.go
  rootchain/payload/payload.go
  rootchain/payload/validator_set_payload.go
  rootchain/proto/event.pb.go
  rootchain/proto/event.proto
  rootchain/sam.go
  rootchain/sam_test.go
  rootchain/samuel/event_data.go
  rootchain/samuel/mock_test.go
  rootchain/samuel/samuel.go
  rootchain/samuel/samuel_test.go
  rootchain/transport/transport.go
  rootchain/types.go
Labels: feature

#760 Transfer v0.5.1 fixes to upstream
  blockchain/blockchain.go
  blockchain/blockchain_test.go
  blockchain/subscription.go
  blockchain/subscription_test.go
  blockchain/testing.go
  command/server/init.go
  consensus/consensus.go
  consensus/dev/dev.go
  consensus/dummy/dummy.go
  consensus/ibft/ibft.go
  consensus/ibft/transport.go
  e2e/broadcast_test.go
  e2e/framework/config.go
  e2e/framework/testserver.go
  e2e/ibft_test.go
  e2e/pos_poa_switch_test.go
  e2e/pos_test.go
  e2e/syncer_test.go
  e2e/transaction_test.go
  e2e/txpool_test.go
  e2e/websocket_test.go
  server/server.go
  txpool/account.go
  txpool/queue.go
  txpool/txpool.go
  txpool/txpool_test.go
Labels: feature

#764 Moved golangci linter config to the separate file
  .github/workflows/main.yml
  .golangci.yml
  Makefile
  command/version/result.go
  helper/enode/enode_test.go
  helper/keccak/keccak.go
  helper/keccak/pool.go
  jsonrpc/eth_endpoint.go
  jsonrpc/txpool_endpoint_test.go
  state/immutable-trie/encoding_test.go
  state/runtime/precompiled/base_test.go
  state/runtime/precompiled/bn256_test.go
  state/runtime/precompiled/modexp_test.go
  state/txn.go
  syncer/client_test.go
  types/buildroot/buildroot_fast.go
  types/header_test.go
  types/receipt.go
Labels: feature

#753 EVM-25 Create state abstraction boundaries for write-ops in the state…
  state/executor.go
  state/testing.go
  state/txn.go
  tests/state_test.go
  tests/testing.go
Labels: feature

#766 Comment begins with a lowercase letter, when it should begin with an uppercase one
  .golangci.yml
Labels: bug fix

#705 Secrets print functionality for ecdsa/bls validator public key address and node id
  command/secrets/init/helper.go
  command/secrets/init/params.go
  command/secrets/output/params.go
  command/secrets/output/result.go
  command/secrets/output/secrets_output.go
  command/secrets/secrets.go
  e2e/framework/testserver.go
  go.mod
  go.sum
  secrets/helper/helper.go
  secrets/local/local.go
Labels: feature
