Repository 0xPolygon/polygon-edge, pull requests merged in 2022-03, with the labels that each got.

#406 Add DNS support for dialling nodes
  network/server.go
  network/server_test.go
Labels: feature

#417 [JSONRPC] Fix websocket subscription
  jsonrpc/filter_manager.go
Labels: hotfix

#435 [Fix] Change default jsonrpc binding to all interfaces (0.0.0.0)
  .gitignore
  command/helper/helper.go
  command/server/config.go
  command/server/init.go
  command/server/server.go
  server/config.go
Labels: bug fix

#437 Change the default value for buffers in pubsub
  network/gossip.go
  network/server.go
Labels: bug fix, feature

#414 Allow wildcard for allow control allowed origins
  command/server/config.go
  jsonrpc/jsonrpc.go
Labels: bug fix

#442 Make the server config init default values for unset params
  command/server/config.go
Labels: hotfix

#412 [Bridge] Signed Arbitrary Message Pool
  bridge/sam/pool.go
  bridge/sam/pool_test.go
  bridge/sam/types.go
  helper/common/address.go
Labels: feature

#448 Fix grpc and jsonprc bindings when set from config file
  command/server/server.go
Labels: hotfix

#460 Update the license info for release v0.3.2
  licenses/bsd_licenses.json
Labels: feature

#466 Start checkpoint process on every epoch start
  blockchain/blockchain.go
  bridge/bridge.go
  bridge/checkpoint/checkpoint.go
  consensus/ibft/bridge.go
  consensus/ibft/poa.go
Labels: feature

#459 [TxPool] Reduce lock time in resetAccounts
  txpool/account.go
  txpool/queue.go
  txpool/txpool.go
  txpool/txpool_test.go
Labels: feature

#468 [Bridge] Checkpoint gossip
  Makefile
  bridge/checkpoint/checkpoint.go
  bridge/checkpoint/transport/proto/transport.pb.go
  bridge/checkpoint/transport/proto/transport.proto
  bridge/checkpoint/transport/transport.go
  bridge/statesync/transport/proto/transport.pb.go
  bridge/statesync/transport/proto/transport_grpc.pb.go
Labels: feature

#397 Update predeployed staking SC
  command/common.go
  command/genesis/genesis.go
  command/genesis/params.go
  command/ibft/switch/ibft_switch.go
  command/ibft/switch/params.go
  command/ibft/switch/result.go
  consensus/ibft/hooks.go
  consensus/ibft/ibft.go
  consensus/ibft/ibft_test.go
  consensus/ibft/pos.go
  e2e/framework/config.go
  e2e/framework/testserver.go
  e2e/pos_test.go
  helper/common/common.go
  helper/staking/staking.go
  jsonrpc/eth_state_test.go
  protocol/service_v1.go
  protocol/syncer.go
  state/executor.go
Labels: feature
