Repository 0xPolygon/polygon-edge, pull requests merged in 2022-01, with the labels that each got.

#284 Add support for EIP-1898
  jsonrpc/codec.go
  jsonrpc/codec_test.go
  jsonrpc/eth_endpoint.go
  jsonrpc/eth_endpoint_test.go
Labels: enhancement

#341 Add support for earliest block number in JSON-RPC module
  jsonrpc/dispatcher.go
  jsonrpc/eth_endpoint.go
  jsonrpc/eth_endpoint_test.go
Labels: enhancement

#326 Feature/inbound outbound peerlimit
  command/helper/config.go
  command/helper/helper.go
  command/server/server_command.go
  network/discovery.go
  network/discovery_test.go
  network/identity.go
  network/server.go
  network/server_test.go
  protocol/syncer_test.go
Labels: feature

#385 Fix linting errors
  blockchain/blockchain.go
  command/genesis/genesis.go
  consensus/ibft/ibft.go
  consensus/ibft/msg_queue.go
  consensus/ibft/proto/utils.go
  consensus/utils.go
  e2e/framework/helper.go
  helper/keccak/keccak.go
  helper/keccak/pool.go
  helper/tests/testing.go
  jsonrpc/dispatcher.go
  jsonrpc/eth_state_test.go
  network/dial_queue.go
  network/discovery.go
  network/gossip.go
  network/gossip_test.go
  network/identity.go
  network/testing.go
  protocol/syncer.go
  protocol/syncer_test.go
  protocol/testing.go
  secrets/hashicorpvault/hashicorp_vault.go
  state/immutable-trie/hasher.go
  state/immutable-trie/state.go
  state/immutable-trie/trie.go
  state/runtime/evm/state.go
  state/txn.go
  txpool/account.go
  txpool/queue.go
  types/buildroot/buildroot_fast.go
  types/header.go
  types/receipt.go
  types/rlp_unmarshal.go
  types/transaction.go
  types/types.go
Labels: hotfix

#374 Fix faulty leave in TestRoutingTable_Disconnected
  network/discovery_test.go
Labels: bug fix

#367 Add real TPS to the loadbot output
  command/loadbot/loadbot_command.go
Labels: feature

#380 [TxPool] Exclude demoted/dropped accounts from block building
  txpool/account.go
  txpool/queue.go
  txpool/txpool.go
  txpool/txpool_test.go
Labels: bug fix
