Repository 0xPolygon/polygon-edge, pull requests merged in 2022-07, with the labels that each got.

#632 Remove parallel execution in e2e tests
  e2e/framework/testserver.go
  e2e/ibft_test.go
Labels: bug fix

#591 Syncer V2
  archive/restore_test.go
  consensus/ibft/ibft.go
  consensus/ibft/ibft_test.go
  network/e2e_testing.go
  network/gossip.go
  network/gossip_test.go
  network/server.go
  network/server_discovery.go
  network/server_identity.go
  protocol/blockchain.go
  protocol/proto/util.go
  protocol/proto/v1.pb.go
  protocol/proto/v1.proto
  protocol/proto/v1_grpc.pb.go
  protocol/service_v1.go
  protocol/skeleton.go
  protocol/sync_peer.go
  protocol/syncer.go
  protocol/syncer_test.go
  protocol/testing.go
  server/system_service.go
  syncer/client.go
  syncer/client_test.go
  syncer/peers.go
  syncer/peers_test.go
  syncer/proto/syncer.pb.go
  syncer/proto/syncer.proto
  syncer/proto/syncer_grpc.pb.go
  syncer/service.go
  syncer/service_test.go
  syncer/syncer.go
  syncer/syncer_test.go
  syncer/types.go
  txpool/txpool.go
  txpool/txpool_test.go
  vendor/google.golang.org/grpc/test/bufconn/bufconn.go
  vendor/modules.txt
Labels: don't merge, feature, breaking change

#652 Add linter guards on problematic error checks
  consensus/ibft/ibft.go
  jsonrpc/eth_endpoint.go
  jsonrpc/jsonrpc.go
  server/server.go
Labels: bug fix

#656 Ignore patch updates from awsgo
  .github/dependabot.yml
Labels: bug fix

#570 Implement removing from filter by ws
  jsonrpc/dispatcher.go
  jsonrpc/eth_endpoint.go
  jsonrpc/filter_manager.go
  jsonrpc/filter_manager_test.go
  jsonrpc/jsonrpc.go
Labels: bug fix

#642 Add custom marshalling and unmarshalling for block Header
  helper/hex/hex.go
  helper/hex/hex_test.go
  types/header.go
  types/header_test.go
  types/receipt.go
Labels: bug fix

#638 Add blockRangeLimit and batchRequestLimit JSON-RPC flags to help prevent node DDoS
  command/server/config/config.go
  command/server/params.go
  command/server/server.go
  jsonrpc/dispatcher.go
  jsonrpc/dispatcher_test.go
  jsonrpc/filter_manager.go
  jsonrpc/filter_manager_test.go
  jsonrpc/jsonrpc.go
  jsonrpc/web3_endpoint_test.go
  server/config.go
  server/server.go
Labels: feature

#641 Compatibility fixes/improvements for JSON/RPC filter polling
  go.mod
  go.sum
  jsonrpc/filter_manager.go
  vendor/github.com/umbracle/ethgo/jsonrpc/eth.go
  vendor/modules.txt
Labels: bug fix
