Repository 0xPolygon/polygon-edge, pull requests merged in 2022-08, with the labels that each got.

#668 Resolve memory creep
  .gitignore
  types/header.go
Labels: bug fix

#678 Make the header timestamp respect time of generation
  consensus/ibft/consensus_backend.go
Labels: bug fix

#677 Update interface of IsValidCommittedSeal and InsertBlock by go-ibft's update
  consensus/ibft/consensus_backend.go
  consensus/ibft/verifier.go
  go.mod
  go.sum
  vendor/github.com/0xPolygon/go-ibft/core/backend.go
  vendor/github.com/0xPolygon/go-ibft/core/ibft.go
  vendor/github.com/0xPolygon/go-ibft/core/state.go
  vendor/github.com/0xPolygon/go-ibft/messages/helpers.go
  vendor/modules.txt
Labels: feature

#682 [Fix] Add disable for batch request limit
  command/server/config/config.go
  command/server/params.go
  command/server/server.go
  jsonrpc/dispatcher.go
  jsonrpc/dispatcher_test.go
  jsonrpc/filter_manager.go
Labels: bug fix

#697 Fix linter errors
  .github/workflows/main.yml
  txpool/event_subscription_test.go
Labels: bug fix

#687 [TxPool] Introduce limit on enqueued transactions
  command/server/config/config.go
  command/server/params.go
  command/server/server.go
  server/config.go
  server/server.go
  txpool/account.go
  txpool/txpool.go
  txpool/txpool_test.go
Labels: bug fix, feature

#690 [TxPool] Reject future transactions during high memory usage
  txpool/txpool.go
  txpool/txpool_test.go
Labels: feature

#692 Permission smart contract deployment
  chain/params.go
  command/root/root.go
  command/whitelist/deployment/deployment.go
  command/whitelist/deployment/params.go
  command/whitelist/deployment/result.go
  command/whitelist/show/params.go
  command/whitelist/show/result.go
  command/whitelist/show/show.go
  command/whitelist/whitelist.go
  helper/config/config.go
  server/server.go
  txpool/txpool.go
  txpool/txpool_test.go
  types/transaction.go
Labels: feature
