Repository 0xPolygon/polygon-edge, pull requests merged in 2022-11, with the labels that each got.

#850 Checking whole files in diff
  .golangci.yml
Labels: feature

#852 [Checkpoints] Parse receipt logs and insert new exit events
  consensus/polybft/block_builder.go
  consensus/polybft/consensus_runtime.go
  consensus/polybft/consensus_runtime_test.go
  consensus/polybft/fsm.go
  consensus/polybft/fsm_test.go
  consensus/polybft/mocks_test.go
  consensus/polybft/state.go
  consensus/polybft/state_test.go
Labels: feature

#839 Fix panic issue due to sending to closed channel
  network/identity/identity.go
  network/server.go
  network/server_discovery.go
  network/server_test.go
  syncer/client.go
  syncer/types.go
Labels: bug fix

#867 Consolidate BLS verification ABI type
  consensus/polybft/state_transaction.go
  state/runtime/precompiled/bls_agg_sigs_verification.go
Labels: feature

#843 EVM 149 - syncer go ibft coordination
  consensus/polybft/consensus_runtime.go
  consensus/polybft/consensus_runtime_test.go
  consensus/polybft/ibft_consensus.go
  consensus/polybft/mocks_test.go
  consensus/polybft/polybft.go
  consensus/polybft/transport.go
Labels: feature

#849 EVM-151 Use (or not) edge hooks support
  consensus/polybft/consensus_runtime.go
  consensus/polybft/polybft.go
Labels: feature

#861 Checkpoint submission
  command/rootchain/helper/txn.go
  consensus/polybft/checkpoint_manager.go
  consensus/polybft/checkpoint_manager_test.go
  consensus/polybft/consensus_runtime.go
  consensus/polybft/consensus_runtime_test.go
  consensus/polybft/extra.go
  consensus/polybft/fsm.go
  consensus/polybft/fsm_test.go
  consensus/polybft/polybft.go
  consensus/polybft/validator_account.go
  consensus/polybft/validators_snapshot_test.go
Labels: feature

#880 Add voting power to the validators
  command/genesis/polybft_params.go
  consensus/polybft/consensus_runtime_test.go
  consensus/polybft/extra.go
  consensus/polybft/extra_test.go
  consensus/polybft/fsm_test.go
  consensus/polybft/mocks_test.go
  consensus/polybft/state_test.go
  consensus/polybft/system_state.go
  consensus/polybft/system_state_test.go
  consensus/polybft/validator_account.go
  consensus/polybft/validator_account_test.go
  consensus/polybft/validator_set.go
Labels: feature

#887 Mock Host implementation in native transfer test
  state/executor.go
  state/runtime/precompiled/native_transfer_test.go
Labels: feature

#885 Disabling hostname prefix in metrics configuration
  server/server_metrics.go
Labels: feature

#856 Remove uber's atomic package
  go.mod
  txpool/txpool.go
  txpool/txpool_test.go
Labels: hotfix

#837 Implement the logic for quorum check
  consensus/ibft/consensus_backend.go
  go.mod
  go.sum
Labels: feature

#891 Integrate go-ibft consensus engine to polybft consensus protocol
  blockchain/blockchain.go
  command/genesis/polybft_params.go
  consensus/ibft/consensus_backend.go
  consensus/polybft/blockchain_wrapper.go
  consensus/polybft/consensus_runtime.go
  consensus/polybft/consensus_runtime_test.go
  consensus/polybft/extra.go
  consensus/polybft/extra_test.go
  consensus/polybft/fsm.go
  consensus/polybft/fsm_test.go
  consensus/polybft/ibft_consensus.go
  consensus/polybft/mocks_test.go
  consensus/polybft/polybft.go
  consensus/polybft/runtime_helpers.go
  consensus/polybft/state.go
  consensus/polybft/state_test.go
  consensus/polybft/state_transaction.go
  consensus/polybft/system_state.go
  consensus/polybft/system_state_test.go
  consensus/polybft/transport.go
  consensus/polybft/validator_metadata.go
  consensus/polybft/validator_metadata_test.go
  consensus/polybft/validator_set.go
  consensus/polybft/wallet/key.go
  e2e-polybft/consensus_test.go
  go.mod
  go.sum
Labels: feature

#810 Fix unstable behaviour in TestContractValidatorStore_CacheChange
  validators/store/contract/contract_test.go
Labels: hotfix

#907 Voting power quorum for signing state sync commitment
  consensus/polybft/consensus_runtime.go
  consensus/polybft/runtime_helpers.go
Labels: feature

#909 Remove dummy Polybft smart contracts
  .gitignore
  command/genesis/polybft_params.go
  consensus/polybft/artifacts.go
  consensus/polybft/polybftcontracts/Dockerfile
  consensus/polybft/polybftcontracts/README.md
  consensus/polybft/polybftcontracts/compile.sh
  consensus/polybft/polybftcontracts/contracts/rootchain/Checkpoint.sol
  consensus/polybft/polybftcontracts/contracts/rootchain/RootchainBridge.sol
  consensus/polybft/polybftcontracts/contracts/sidechain/ERC20Bridge.sol
  consensus/polybft/polybftcontracts/contracts/sidechain/GasUsageBenchmark.sol
  consensus/polybft/polybftcontracts/contracts/sidechain/MintERC20.sol
  consensus/polybft/polybftcontracts/contracts/sidechain/SidechainBridge.sol
  consensus/polybft/polybftcontracts/contracts/sidechain/Validator.sol
  consensus/polybft/polybftcontracts/hardhat.config.js
  consensus/polybft/polybftcontracts/package-lock.json
  consensus/polybft/polybftcontracts/package.json
  consensus/polybft/polybftcontracts/scripts/sample-script.js
Labels: feature

#911 Align pointer receivers in validator metadata
  consensus/polybft/validator_metadata.go
Labels: feature

#908 Jsonrpc fix race conditions
  jsonrpc/filter_manager.go
  jsonrpc/filter_manager_test.go
  jsonrpc/mocks_test.go
Labels: hotfix

#913 Deprecate sql driver types
  types/receipt.go
  types/types.go
Labels: hotfix

#910 EVM-152 Fix Unit Tests
  consensus/polybft/fsm.go
  consensus/polybft/fsm_test.go
  consensus/polybft/hash.go
  consensus/polybft/hash_test.go
  consensus/polybft/mocks_test.go
  consensus/polybft/polybft_test.go
  consensus/polybft/wallet/key_test.go
Labels: bug fix

#912 Introduce local development cluster script
  command/genesis/polybft_params.go
  scripts/cluster
Labels: feature

#919 Revert removal of MarshalText function
  go.mod
  go.sum
  jsonrpc/testsuite/block-empty.json
  jsonrpc/testsuite/block-with-txn-hashes.json
  jsonrpc/types_test.go
  types/header.go
Labels: bug fix

#930 Fix assigned boot nodes port number in genesis
  command/genesis/polybft_params.go
Labels: bug fix

#894 Proposer selection
  consensus/polybft/consensus_runtime.go
  consensus/polybft/consensus_runtime_test.go
  consensus/polybft/extra.go
  consensus/polybft/extra_test.go
  consensus/polybft/fsm.go
  consensus/polybft/fsm_test.go
  consensus/polybft/mocks_test.go
  consensus/polybft/polybft_test.go
  consensus/polybft/safe_math.go
  consensus/polybft/safe_math_test.go
  consensus/polybft/validator_metadata.go
  consensus/polybft/validator_set.go
  consensus/polybft/validator_set_test.go
  consensus/polybft/validators_snapshot_test.go
Labels: feature

#904 Polybft consensus voting power quorum size
  command/genesis/polybft_params.go
  consensus/polybft/consensus_runtime.go
  consensus/polybft/consensus_runtime_test.go
  consensus/polybft/contracts_initializer.go
  consensus/polybft/extra.go
  consensus/polybft/extra_test.go
  consensus/polybft/fsm.go
  consensus/polybft/fsm_test.go
  consensus/polybft/mocks_test.go
  consensus/polybft/polybft.go
  consensus/polybft/runtime_helpers.go
  consensus/polybft/validator_set.go
  consensus/polybft/validator_set_test.go
  e2e-polybft/consensus_test.go
Labels: feature

#923 Add unit tests for jsonrpc transaction encoding
  jsonrpc/testsuite/block-with-txn-bodies.json
  jsonrpc/testsuite/transaction-pending.json
  jsonrpc/testsuite/transaction-sealed.json
  jsonrpc/types_test.go
  server/system_service.go
Labels: feature

#935 Fix unit test for event tracker
  consensus/polybft/event_tracker_test.go
  go.mod
  go.sum
Labels: bug fix

#918 Add performance tests to devnet deployments
  .github/workflows/deploy.devnet.yml
  .github/workflows/deploy.testnet.yml
Labels: don't merge, feature

#939 Track updates for validators
  consensus/polybft/extra.go
  consensus/polybft/extra_test.go
  consensus/polybft/mocks_test.go
  consensus/polybft/validator_metadata.go
  consensus/polybft/validator_metadata_test.go
Labels: feature

#949 Docker setup: Wait for genesis file to exist before starting nodes
  docker/local/docker-compose.yml
  docker/local/polygon-edge.sh
Labels: bug fix

#926 EVM-220 TestClusterBlockSync/BLS fails in voting power branch
  consensus/ibft/consensus_backend.go
  consensus/polybft/consensus_runtime.go
  go.mod
  go.sum
Labels: bug fix

#971 Align `v3-parity` with `develop` branch
  .github/workflows/deploy.devnet.yml
  .github/workflows/deploy.testnet.yml
  docker/local/docker-compose.yml
  docker/local/polygon-edge.sh
Labels: feature, hotfix

#836 Debug tracing
  go.sum
  jsonrpc/debug_endpoint.go
  jsonrpc/debug_endpoint_test.go
  jsonrpc/dispatcher.go
  jsonrpc/eth_blockchain_test.go
  jsonrpc/eth_endpoint.go
  jsonrpc/eth_endpoint_test.go
  jsonrpc/eth_state_test.go
  jsonrpc/eth_txpool_test.go
  jsonrpc/filter_manager.go
  jsonrpc/helper.go
  jsonrpc/helper_test.go
  jsonrpc/jsonrpc.go
  jsonrpc/mocks_test.go
  server/server.go
  state/executor.go
  state/runtime/evm/evm.go
  state/runtime/evm/evm_test.go
  state/runtime/evm/instructions.go
  state/runtime/evm/instructions_test.go
  state/runtime/evm/state.go
  state/runtime/evm/state_test.go
  state/runtime/runtime.go
  state/runtime/tracer/structtracer/tracer.go
  state/runtime/tracer/structtracer/tracer_test.go
  state/runtime/tracer/types.go
Labels: feature

#967 Modify e2e tests to accommodate the execution of the state syncs
  consensus/polybft/consensus_runtime_test.go
  consensus/polybft/state.go
  consensus/polybft/state_test.go
  e2e-polybft/bridge_test.go
  types/state_sync.go
Labels: feature

#966 improving workflow dependency
  .github/workflows/deploy.devnet.eph.yml
  .github/workflows/deploy.devnet.yml
  .github/workflows/deploy.testnet.yml
Labels: feature

#978 Replace BLS library with github.com/kilic/bn254
  consensus/polybft/signer/common.go
  consensus/polybft/signer/private.go
  consensus/polybft/signer/public.go
  consensus/polybft/signer/signature.go
  consensus/polybft/signer/signature_test.go
  consensus/polybft/signer/utils.go
  go.mod
  go.sum
  state/runtime/precompiled/bls_agg_sigs_verification_test.go
  state/runtime/precompiled/fixtures/blsAggSigns.json
Labels: bug fix
