Repository 0xPolygon/polygon-edge, pull requests merged in 2022-05, with the labels that each got.

#485 Remove waiting for the next block in e2e tests
  e2e/framework/config.go
  e2e/framework/testserver.go
  e2e/pos_test.go
  e2e/txpool_test.go
Labels: bug fix

#531 Update GH actions script
  .github/workflows/main.yml
Labels: feature

#524 Remove total difficulty from the best peer calculation
  protocol/proto/v1.pb.go
  protocol/proto/v1.proto
  protocol/proto/v1_grpc.pb.go
  protocol/syncer.go
  protocol/testing.go
Labels: bug fix

#534 Remove unused directory from folder generation
  server/server.go
Labels: bug fix

#526 Test runtime shaving
  .github/workflows/main.yml
  archive/backup_test.go
  chain/chain_test.go
  crypto/crypto_test.go
  crypto/txsigner_test.go
  e2e/broadcast_test.go
  e2e/encoding_test.go
  e2e/framework/helper.go
  e2e/framework/testserver.go
  e2e/genesis_test.go
  e2e/ibft_test.go
  e2e/logs_test.go
  e2e/pos_poa_switch_test.go
  e2e/pos_test.go
  e2e/transaction_test.go
  e2e/txpool_test.go
  e2e/websocket_test.go
  helper/tests/testing.go
  jsonrpc/codec_test.go
  jsonrpc/dispatcher_test.go
  jsonrpc/eth_blockchain_test.go
  jsonrpc/eth_endpoint_test.go
  jsonrpc/eth_state_test.go
  jsonrpc/txpool_endpoint_test.go
  protocol/syncer_test.go
  state/immutable-trie/encoding_test.go
  state/runtime/evm/evm_test.go
  state/runtime/precompiled/testing.go
  state/testing.go
  state/transition_test.go
  tests/evm_test.go
  tests/state_test.go
  txpool/event_subscription_test.go
  txpool/txpool_test.go
  types/types_test.go
Labels: feature

#525 [Feature] Added support for YAML/YML config file format and configurable server log output to file
  .gitignore
  Makefile
  command/default.go
  command/server/config.go
  command/server/config/config.go
  command/server/export/export.go
  command/server/export/params.go
  command/server/export/result.go
  command/server/init.go
  command/server/params.go
  command/server/server.go
  go.mod
  server/config.go
  server/server.go
  vendor/modules.txt
Labels: feature

#541 [TxPool] Self pruning stuck transactions
  txpool/account.go
  txpool/txpool.go
  txpool/txpool_test.go
Labels: feature

#549 [IBFT] Introduce quorum calculation switch
  command/ibft/ibft.go
  command/ibft/quorum/ibft_quorum.go
  command/ibft/quorum/params.go
  command/ibft/quorum/result.go
  consensus/ibft/ibft.go
  consensus/ibft/ibft_test.go
  consensus/ibft/sign.go
  consensus/ibft/sign_test.go
  consensus/ibft/state.go
  consensus/ibft/state_test.go
Labels: feature, hotfix

#528 Add txHash to rlp store marshal/unmarshal
  jsonrpc/filter_manager.go
  jsonrpc/filter_manager_test.go
  jsonrpc/mocks_test.go
  types/rlp_encoding_test.go
  types/rlp_marshal_storage.go
  types/rlp_unmarshal_storage.go
Labels: hotfix, breaking change

#545 [TxPool] Fix ErrAlreadyUnknown in tests
  txpool/txpool.go
  txpool/txpool_test.go
Labels: bug fix

#538 Implement eth_getFilterLogs
  jsonrpc/eth_blockchain_test.go
  jsonrpc/eth_endpoint.go
  jsonrpc/filter_manager.go
  jsonrpc/filter_manager_test.go
Labels: feature

#566 Add json tags for Header struct
  types/header.go
Labels: bug fix
