Repository 0xPolygon/polygon-edge, pull requests merged in 2022-10, with the labels that each got.

#718 [Rootnet Staking] SAM Pool
  rootchain/sampool/bucket.go
  rootchain/sampool/pool.go
  rootchain/sampool/pool_test.go
Labels: feature

#724 [Rootnet Staking] State transactions
  state/executor.go
  types/buildroot/buildroot.go
  types/receipt.go
  types/rlp_encoding_test.go
  types/rlp_marshal.go
  types/rlp_marshal_storage.go
  types/rlp_unmarshal.go
  types/rlp_unmarshal_storage.go
  types/transaction.go
Labels: feature

#763 EVM-42 Remove WebSocket filter with closed connection
  jsonrpc/dispatcher_test.go
  jsonrpc/filter_manager.go
  jsonrpc/filter_manager_test.go
Labels: bug fix

#744 Fix the size of return value by eth_getStorageAt
  jsonrpc/eth_endpoint.go
Labels: bug fix

#737 [Rootnet Staking] Event Tracker
  rootchain/tracker/rootchain.go
  rootchain/tracker/rootchain_test.go
  rootchain/tracker/tracker.go
  rootchain/tracker/tracker_test.go
Labels: feature

#745 [FIX] Disable debug/vars
  jsonrpc/jsonrpc.go
Labels: bug fix

#707 [Feature] Datadog profiler
  go.mod
  go.sum
  server/server.go
  server/server_metrics.go
Labels: feature

#536 Custom contract predeployment
  command/genesis/genesis.go
  command/genesis/params.go
  command/genesis/predeploy/genesis_predeploy.go
  command/genesis/predeploy/params.go
  command/genesis/predeploy/result.go
  e2e/framework/config.go
  e2e/framework/ibft.go
  e2e/framework/testserver.go
  e2e/genesis_test.go
  e2e/metadata/StressTest.sol
  e2e/metadata/predeploy.sol
  e2e/metadata/predeploy_abi.json
  e2e/metadata/sample.sol
  helper/predeployment/argparser.go
  helper/predeployment/argparser_test.go
  helper/predeployment/predeployment.go
  state/executor.go
  state/txn.go
Labels: feature

#672 Add support for better client version details
  jsonrpc/dispatcher.go
  jsonrpc/dispatcher_test.go
  jsonrpc/jsonrpc.go
  jsonrpc/jsonrpc_test.go
  jsonrpc/web3_endpoint.go
  jsonrpc/web3_endpoint_test.go
  server/server.go
Labels: bug fix

#779 Adding netgo build tag for Linux releases
  .goreleaser.yml
Labels: feature

#765 Initial Workflow Rework
  .github/workflows/build.yml
  .github/workflows/ci.yml
  .github/workflows/cla.yml
  .github/workflows/deploy.devnet.yml
  .github/workflows/deploy.testnet.yml
  .github/workflows/deploy_edgenet.yaml
  .github/workflows/e2e.yaml
  .github/workflows/lint.yml
  .github/workflows/loadbot.yml
  .github/workflows/main.yml
  .github/workflows/pandoras_box.yml
  .github/workflows/release.yml
  .github/workflows/security.yml
  .github/workflows/test.yml
Labels: don't merge, feature

#788 removing condition for CI workflow to run
  .github/workflows/ci.yml
Labels: feature

#775 [FIX] Bootnode re-discovery issue
  go.mod
  network/discovery/discovery.go
  network/server.go
  network/server_discovery.go
  network/testing/testing.go
Labels: bug fix

#791 Resolve invalid snapshot pruning
  validators/store/snapshot/types.go
  validators/store/snapshot/types_test.go
Labels: hotfix

#809 EVM-57 PolyBft state transactions introduction
  blockchain/blockchain.go
  command/genesis/genesis.go
  command/genesis/polybft_params.go
  consensus/polybft/block_builder.go
  consensus/polybft/consensus_runtime.go
  consensus/polybft/fsm.go
  consensus/polybft/polybft.go
  consensus/polybft/signer/common.go
  consensus/polybft/signer/public.go
  consensus/polybft/signer/signature_test.go
  consensus/polybft/signer/utils_test.go
  consensus/polybft/system_state.go
  state/executor.go
  types/receipt.go
  types/rlp_encoding_test.go
  types/rlp_marshal.go
  types/rlp_unmarshal.go
  types/transaction.go
Labels: feature

#778 EVM-69 Fix panic issue in opReturnDataCopy
  state/runtime/evm/instructions.go
  state/runtime/evm/instructions_test.go
  state/runtime/evm/state.go
Labels: bug fix

#828 EVM-129 Implement bridge workflow
  command/genesis/genesis.go
  command/genesis/params.go
  command/genesis/polybft_params.go
  command/rootchain/emit/emit.go
  command/rootchain/helper/metadata.go
  command/rootchain/helper/txn.go
  command/rootchain/server/server.go
  e2e-polybft/bridge_test.go
  e2e-polybft/framework/test-bootnode.go
  e2e-polybft/framework/test-bridge.go
  e2e-polybft/framework/test-cluster.go
  e2e-polybft/framework/test-server.go
  e2e-polybft/network_test.go
  e2e-polybft/txpool_test.go
  go.mod
  go.sum
Labels: feature

#825 Transfer unit tests from v3 to Edge
  .github/workflows/test.yml
  Makefile
  consensus/polybft/bitmap/bitmap_test.go
  consensus/polybft/block_builder.go
  consensus/polybft/consensus_runtime.go
  consensus/polybft/consensus_runtime_test.go
  consensus/polybft/event_tracker_test.go
  consensus/polybft/extra_test.go
  consensus/polybft/fsm.go
  consensus/polybft/fsm_test.go
  consensus/polybft/helpers_test.go
  consensus/polybft/merkle_tree_test.go
  consensus/polybft/mocks.go
  consensus/polybft/mocks_test.go
  consensus/polybft/polybft.go
  consensus/polybft/polybft_test.go
  consensus/polybft/signer/private.go
  consensus/polybft/signer/private_test.go
  consensus/polybft/signer/public.go
  consensus/polybft/signer/public_test.go
  consensus/polybft/signer/signature_test.go
  consensus/polybft/signer/utils_test.go
  consensus/polybft/state_test.go
  consensus/polybft/state_transaction.go
  consensus/polybft/state_transaction_test.go
  consensus/polybft/system_state_test.go
  consensus/polybft/test_utils.go
  consensus/polybft/validator_account_test.go
  consensus/polybft/validators_snapshot_test.go
  consensus/polybft/wallet/account_test.go
  go.mod
  go.sum
  setup-ci.sh
  state/executor.go
  state/runtime/runtime.go
Labels: feature

#822 Recognize JSON Log format flag in downstream server logs
  command/helper/helper.go
  command/server/config/config.go
  command/server/params.go
  command/server/server.go
  server/config.go
  server/server.go
Labels: bug fix

#844 [Checkpointing] JSON RPC point for generating exit proofs
  consensus/consensus.go
  consensus/dev/dev.go
  consensus/dummy/dummy.go
  consensus/ibft/ibft.go
  consensus/polybft/consensus_runtime.go
  consensus/polybft/consensus_runtime_test.go
  consensus/polybft/polybft.go
  jsonrpc/bridge_endpoint.go
  jsonrpc/bridge_endpoint_test.go
  jsonrpc/dispatcher.go
  jsonrpc/jsonrpc.go
  jsonrpc/mocks_test.go
  server/server.go
Labels: feature

#838 [Checkpointing] `ExitEvent` storage and proof generation
  consensus/consensus.go
  consensus/dev/dev.go
  consensus/dummy/dummy.go
  consensus/ibft/ibft.go
  consensus/polybft/consensus_runtime.go
  consensus/polybft/consensus_runtime_test.go
  consensus/polybft/fsm.go
  consensus/polybft/fsm_test.go
  consensus/polybft/merkle_tree.go
  consensus/polybft/polybft.go
  consensus/polybft/state.go
  consensus/polybft/state_test.go
  jsonrpc/bridge_endpoint.go
  jsonrpc/bridge_endpoint_test.go
  jsonrpc/dispatcher.go
  jsonrpc/jsonrpc.go
  jsonrpc/mocks_test.go
  server/server.go
Labels: feature

#840 Checkpoint data signing
  command/e2e/register_validator.go
  command/genesis/polybft_params.go
  command/rootchain/initcontracts/init_contracts.go
  consensus/polybft/blockchain_wrapper.go
  consensus/polybft/consensus_runtime.go
  consensus/polybft/contracts_initializer.go
  consensus/polybft/extra.go
  consensus/polybft/extra_test.go
  consensus/polybft/fsm.go
  consensus/polybft/fsm_test.go
  consensus/polybft/mocks_test.go
  consensus/polybft/polybft.go
  consensus/polybft/polybft_test.go
  consensus/polybft/signer/public.go
  consensus/polybft/signer/public_test.go
  consensus/polybft/validator_account.go
  consensus/polybft/validator_account_test.go
  e2e-polybft/bridge_test.go
Labels: feature
