Repository 0xPolygon/polygon-edge, pull requests merged in 2022-12, with the labels that each got.

#985 Removing `GenesisTarget` and adding the `NodeID` field to `Validator` struct
  command/genesis/polybft_params.go
  command/genesis/utils.go
  command/rootchain/initcontracts/init_contracts.go
  consensus/polybft/polybft_config.go
  e2e-polybft/bridge_test.go
  e2e-polybft/framework/test-cluster.go
Labels: bug fix

#925 Normalize block timestamps
  consensus/ibft/consensus_backend.go
  consensus/ibft/consensus_backend_test.go
  server/system_service.go
Labels: bug fix

#989 Provide rootchain IP address from CLI
  command/genesis/genesis.go
  command/genesis/params.go
  command/genesis/polybft_params.go
  command/rootchain/emit/emit.go
  command/rootchain/emit/params.go
  command/rootchain/fund/fund.go
  command/rootchain/fund/params.go
  command/rootchain/helper/txn.go
  command/rootchain/initcontracts/init_contracts.go
  command/rootchain/initcontracts/params.go
  consensus/polybft/checkpoint_manager.go
  consensus/polybft/checkpoint_manager_test.go
  consensus/polybft/consensus_runtime.go
  consensus/polybft/consensus_runtime_test.go
  consensus/polybft/polybft.go
  consensus/polybft/polybft_config.go
  e2e-polybft/bridge_test.go
  e2e-polybft/framework/test-cluster.go
  e2e-polybft/txpool_test.go
  scripts/cluster
  txrelayer/txrelayer.go
Labels: bug fix, breaking change

#999 Add london hardfork to chain config
  chain/params.go
  tests/testing.go
Labels: feature

#992 Fix pending checkpoints submission
  consensus/polybft/checkpoint_manager.go
  consensus/polybft/checkpoint_manager_test.go
Labels: bug fix

#1001 Fix eth_sendRawTransaction from uninitialized address
  server/server.go
Labels: bug fix

#1009 Detect empty proposal on IsValidProposalHash and BuildPrePrepareMessage
  consensus/polybft/consensus_runtime.go
  consensus/polybft/consensus_runtime_test.go
Labels: bug fix

#1027 Simplify `deliverMessage` signature
  consensus/polybft/consensus_runtime.go
  consensus/polybft/consensus_runtime_test.go
  consensus/polybft/transport.go
Labels: bug fix

#1033 adding osuergo build tag to goreleaser
  .goreleaser.yml
Labels: hotfix

#1026 RLP Marshal/Unmarshal update field in `ValidatorSetDelta`
  consensus/polybft/extra.go
  consensus/polybft/extra_test.go
Labels: bug fix

#1039 Remove unused checkpoint fields from `epochMetadata`
  consensus/polybft/consensus_runtime.go
Labels: feature

#1042 IBFT extra unmarshalRLP error
  consensus/ibft/consensus_backend.go
  consensus/ibft/ibft.go
Labels: bug fix

#1040 Expose `PolyBFT` metrics to Prometheus API
  consensus/polybft/checkpoint_manager.go
  consensus/polybft/consensus_metrics.go
  consensus/polybft/consensus_runtime.go
  consensus/polybft/consensus_runtime_test.go
Labels: feature

#991 Remove loadbot
  .github/workflows/loadbot.yml
  command/loadbot/abis.go
  command/loadbot/deploy_contract.go
  command/loadbot/duration.go
  command/loadbot/execution.go
  command/loadbot/generator/base.go
  command/loadbot/generator/contract_txn_generator.go
  command/loadbot/generator/deploy_generator.go
  command/loadbot/generator/erc_generators.go
  command/loadbot/generator/generator.go
  command/loadbot/generator/transfer_generator.go
  command/loadbot/generators.go
  command/loadbot/helper.go
  command/loadbot/loadbot_command.go
  command/loadbot/params.go
  command/loadbot/result.go
  command/root/root.go
Labels: breaking change

#1050 EVM-308 Add commands we are missing
  command/polybft/polybft_command.go
  command/root/root.go
  command/sidechain/helper.go
  command/sidechain/staking/params.go
  command/sidechain/staking/stake.go
  command/sidechain/unstaking/params.go
  command/sidechain/unstaking/unstake.go
  command/sidechain/validators/params.go
  command/sidechain/validators/validator_info.go
  command/sidechain/withdraw/params.go
  command/sidechain/withdraw/withdraw.go
  consensus/polybft/state_transaction.go
  txrelayer/txrelayer.go
Labels: feature

#1043 Add appropriate prefixes to the Edge metrics
  consensus/ibft/ibft.go
  network/server.go
  network/server_identity.go
  txpool/txpool.go
Labels: breaking change

#1053 Fix loop closure violations in unit tests
  consensus/polybft/extra_test.go
  consensus/polybft/system_state_test.go
Labels: bug fix

#1052 Pending checkpoints submission E2E test
  e2e-polybft/bridge_test.go
  e2e-polybft/framework/test-bridge.go
  e2e-polybft/framework/test-cluster.go
  go.mod
Labels: feature

#1005 Decouple rootchain contracts deployment from development environment
  .gitignore
  command/genesis/genesis.go
  command/genesis/params.go
  command/genesis/polybft_params.go
  command/genesis/utils.go
  command/polybftmanifest/manifest_init.go
  command/root/root.go
  command/rootchain/emit/emit.go
  command/rootchain/emit/params.go
  command/rootchain/helper/metadata.go
  command/rootchain/helper/txn.go
  command/rootchain/initcontracts/init_contracts.go
  command/rootchain/initcontracts/params.go
  consensus/polybft/README.md
  consensus/polybft/checkpoint_manager.go
  consensus/polybft/checkpoint_manager_test.go
  consensus/polybft/consensus_runtime.go
  consensus/polybft/consensus_runtime_test.go
  consensus/polybft/contractsapi/gen_sc_data.go
  consensus/polybft/polybft.go
  consensus/polybft/polybft_config.go
  consensus/polybft/polybft_test.go
  e2e-polybft/README.md
  e2e-polybft/bridge_test.go
  e2e-polybft/framework/test-bridge.go
  e2e-polybft/framework/test-cluster.go
  scripts/cluster
Labels: bug fix, breaking change

#1018 EVM-302 Save proposer priorities after each block
  consensus/polybft/consensus_runtime.go
  consensus/polybft/consensus_runtime_test.go
  consensus/polybft/fsm.go
  consensus/polybft/polybft.go
  consensus/polybft/proposer_calculator.go
  consensus/polybft/proposer_calculator_test.go
  consensus/polybft/state.go
  consensus/polybft/state_test.go
  consensus/polybft/validator_set.go
  consensus/polybft/validator_set_test.go
Labels: feature

#1058 Consolidate `ExtendByteSlice` implementations
  consensus/polybft/bitmap/bitmap.go
  consensus/polybft/bitmap/bitmap_test.go
  helper/common/common.go
  helper/common/common_test.go
  state/immutable-trie/trie.go
  state/runtime/evm/bitmap.go
  state/runtime/evm/state.go
  state/runtime/precompiled/precompiled.go
Labels: bug fix

#1061 Remove `readContractBytecode` from rootchain init contracts command
  command/rootchain/initcontracts/init_contracts.go
Labels: bug fix

#1047 Evm 303: Fix race conditions after a block is inserted
  consensus/polybft/consensus_runtime.go
  consensus/polybft/consensus_runtime_test.go
  consensus/polybft/polybft.go
  consensus/polybft/proposer_calculator.go
Labels: bug fix

#1048 Feature/validator set changes
  consensus/polybft/proposer_calculator.go
  consensus/polybft/proposer_calculator_test.go
Labels: feature

#1054 Fix segmentation fault panic on `ValidateSender`
  consensus/polybft/consensus_runtime.go
  consensus/polybft/fsm.go
  consensus/polybft/polybft.go
  consensus/polybft/transport.go
  consensus/polybft/validator_set.go
  consensus/polybft/wallet/key.go
Labels: bug fix

#1064 RFC173 Checkpoint consensus issue
  consensus/polybft/consensus_runtime.go
  consensus/polybft/consensus_runtime_test.go
  consensus/polybft/fsm.go
  consensus/polybft/fsm_test.go
  consensus/polybft/mocks_test.go
Labels: feature

#1044 Implement the relayer
  command/server/config/config.go
  command/server/init.go
  command/server/params.go
  command/server/server.go
  consensus/consensus.go
  consensus/polybft/consensus_runtime.go
  consensus/polybft/statesyncrelayer/state_sync_relayer.go
  consensus/polybft/statesyncrelayer/state_sync_relayer_test.go
  server/config.go
  server/server.go
  tracker/event_tracker.go
  tracker/event_tracker_test.go
Labels: feature

#1060 Remove voting power scaling
  chain/chain.go
  chain/chain_test.go
  command/rootchain/initcontracts/init_contracts.go
  consensus/polybft/consensus_runtime.go
  consensus/polybft/consensus_runtime_test.go
  consensus/polybft/contracts_initializer.go
  consensus/polybft/extra.go
  consensus/polybft/extra_test.go
  consensus/polybft/fsm.go
  consensus/polybft/fsm_test.go
  consensus/polybft/mocks_test.go
  consensus/polybft/polybft.go
  consensus/polybft/polybft_config.go
  consensus/polybft/proposer_calculator.go
  consensus/polybft/proposer_calculator_test.go
  consensus/polybft/safe_math.go
  consensus/polybft/safe_math_test.go
  consensus/polybft/system_state.go
  consensus/polybft/system_state_test.go
  consensus/polybft/validator_metadata.go
  consensus/polybft/validator_metadata_test.go
  consensus/polybft/validator_set.go
  consensus/polybft/validator_set_test.go
  helper/common/common.go
  helper/common/common_test.go
Labels: bug fix

#1051 Epikichi/edge 988 add polybft consensus support to edge
  Makefile
  docker/README.md
  docker/local/Dockerfile
  docker/local/docker-compose.yml
  docker/local/polygon-edge.sh
  scripts/README.md
  scripts/cluster
Labels: feature

#1075 Implement `TestE2E_Bridge_ChangeVotingPower`
  command/genesis/genesis.go
  command/genesis/params.go
  command/genesis/polybft_params.go
  command/genesis/utils.go
  command/polybftmanifest/manifest_init.go
  command/sidechain/helper.go
  command/sidechain/validators/params.go
  command/sidechain/validators/validator_info.go
  consensus/polybft/consensus_runtime.go
  consensus/polybft/contracts_initializer.go
  consensus/polybft/fsm.go
  consensus/polybft/polybft_config.go
  consensus/polybft/system_state.go
  e2e-polybft/bridge_test.go
  e2e-polybft/framework/test-bridge.go
  e2e-polybft/framework/test-cluster.go
  e2e-polybft/framework/test-server.go
Labels: feature

#1078 Fix parallel table tests
  syncer/service_test.go
  validators/store/snapshot/helper_test.go
  validators/store/snapshot/snapshot_test.go
Labels: bug fix

#1077 Remove unnecessary panics from polybft
  command/e2e/register_validator.go
  consensus/polybft/blockchain_wrapper.go
  consensus/polybft/fsm.go
  consensus/polybft/polybft.go
  consensus/polybft/state.go
  consensus/polybft/state_transaction.go
  consensus/polybft/system_state_test.go
  consensus/polybft/validators_snapshot_test.go
Labels: bug fix

#997 Modify snapshot calculation for dynamic epoch
  consensus/polybft/consensus_runtime.go
  consensus/polybft/helpers_test.go
  consensus/polybft/mocks_test.go
  consensus/polybft/polybft_test.go
  consensus/polybft/proposer_calculator.go
  consensus/polybft/runtime_helpers.go
  consensus/polybft/runtime_helpers_test.go
  consensus/polybft/state.go
  consensus/polybft/state_test.go
  consensus/polybft/validators_snapshot.go
  consensus/polybft/validators_snapshot_test.go
Labels: feature

#897 Dynamic epoch size
  consensus/polybft/checkpoint_manager_test.go
  consensus/polybft/consensus_runtime.go
  consensus/polybft/consensus_runtime_test.go
  consensus/polybft/helpers_test.go
  consensus/polybft/mocks_test.go
  consensus/polybft/polybft.go
  consensus/polybft/polybft_test.go
  consensus/polybft/proposer_calculator.go
  consensus/polybft/runtime_helpers.go
  consensus/polybft/runtime_helpers_test.go
  consensus/polybft/state.go
  consensus/polybft/state_test.go
  consensus/polybft/validators_snapshot.go
  consensus/polybft/validators_snapshot_test.go
Labels: feature
