Repository 0xPolygon/polygon-edge, pull requests merged in 2022-02, with the labels that each got.

#383 Refactor parts of the trie package
  state/immutable-trie/encoding.go
  state/immutable-trie/encoding_test.go
  state/immutable-trie/hasher.go
  state/immutable-trie/storage.go
  state/immutable-trie/trie.go
Labels: hotfix

#399 Fix up the block timestamp to be read in seconds
  blockchain/blockchain.go
  command/helper/config.go
  command/server/server_command.go
  consensus/consensus.go
  consensus/ibft/ibft.go
  consensus/metrics.go
  consensus/utils.go
  server/config.go
Labels: hotfix

#394 Update the PR template
  .github/pull_request_template.md
Labels: feature

#400 Added some jsonrpc unit tests
  jsonrpc/dispatcher_test.go
  jsonrpc/eth_blockchain_test.go
  jsonrpc/eth_endpoint.go
  jsonrpc/eth_state_test.go
  jsonrpc/jsonrpc.go
  jsonrpc/query_test.go
  jsonrpc/txpool_endpoint.go
  jsonrpc/txpool_endpoint_test.go
  jsonrpc/web3_endpoint_test.go
Labels: bug fix

#368 Add cors middleware support in JSON-RPC server
  command/helper/config.go
  command/helper/helper.go
  command/server/server_command.go
  jsonrpc/jsonrpc.go
  server/config.go
  server/server.go
Labels: don't merge, feature

#373 Remove traces of waitUntilDone
  command/txpool/txpool_subscribe.go
  txpool/event_manager.go
  txpool/event_subscription_test.go
  txpool/mock_test.go
  txpool/proto/operator.pb.go
  txpool/proto/operator.proto
  txpool/queue.go
  txpool/txpool.go
  txpool/txpool_test.go
Labels: bug fix

#334 IBFT PoA/PoS switch
  blockchain/blockchain.go
  blockchain/testing.go
  command/genesis/genesis.go
  command/helper/helper.go
  command/ibft/ibft_switch.go
  command/util/commands.go
  consensus/consensus.go
  consensus/dev/dev.go
  consensus/dummy/dummy.go
  consensus/ibft/hooks.go
  consensus/ibft/ibft.go
  consensus/ibft/ibft_test.go
  consensus/ibft/poa.go
  consensus/ibft/pos.go
  consensus/ibft/snapshot.go
  consensus/ibft/snapshot_test.go
  e2e/framework/testserver.go
  e2e/pos_poa_switch_test.go
  helper/common/common.go
  helper/staking/staking.go
  state/executor.go
Labels: feature

#421 Fix minor test wait bug
  txpool/txpool_test.go
Labels: bug fix

#413 Upgrade minimum go version to 1.16
  .github/workflows/main.yml
  go.mod
  go.sum
Labels: feature

#407 Display version, our license, and vendor attributions in version command
  .goreleaser.yml
  Makefile
  command/license/license.go
  command/util/commands.go
  command/version/version.go
  generate_dependency_licenses.sh
  jsonrpc/web3_endpoint.go
  jsonrpc/web3_endpoint_test.go
  licenses/bsd_licenses.json
  licenses/licenses.go
  main.go
  version/version.go
  versioning/versioning.go
Labels: feature

#405 Allow longer domain suffix for server --dns value.
  helper/flags/flags.go
  helper/flags/flags_test.go
Labels: bug fix

#345 Reject eth_sendTransaction jsonrpc call with error
  e2e/encoding_test.go
  e2e/logs_test.go
  jsonrpc/eth_endpoint.go
  jsonrpc/eth_txpool_test.go
Labels: bug fix
