Repository 0xPolygon/polygon-edge, pull requests merged in 2023-11, with the labels that each got.

#2024 Revert `seal` parameter removal
  command/regenesis/howtotest.md
  command/server/config/config.go
  command/server/params.go
  command/server/server.go
  consensus/polybft/README.md
  docker/local/docker-compose.yml
Labels: feature

#2027 Migrate to SonarCloud
  .github/workflows/test.yml
  sonar-project.properties
Labels: chore

#2030 Final touches to Sonarcloud
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
  .github/workflows/test.yml
  sonar-project.properties
Labels: bug fix
