Repository 0xPolygon/polygon-edge, pull requests merged in 2023-10, with the labels that each got.

#1925 Provide race and shuffle flags when running unit tests
  Makefile
  blockchain/blockchain.go
  blockchain/blockchain_test.go
  chain/params.go
  command/bridge/deposit/erc20/deposit_erc20.go
  command/rootchain/fund/fund.go
  consensus/ibft/signer/extra_test.go
  consensus/ibft/signer/signer_test.go
  consensus/polybft/block_builder.go
  consensus/polybft/fsm.go
  consensus/polybft/polybft.go
  consensus/polybft/signer/signature_test.go
  forkmanager/fork.go
  gasprice/gasprice.go
  jsonrpc/debug_endpoint.go
  jsonrpc/filter_manager.go
  jsonrpc/types.go
  network/e2e_testing.go
  network/gossip_test.go
  scripts/fuzzAll
  state/runtime/tracer/structtracer/tracer.go
  syncer/client_test.go
  syncer/peers_test.go
  txpool/event_subscription_test.go
  txpool/operator.go
  txpool/queue_account.go
  txpool/txpool.go
  txpool/txpool_test.go
  txrelayer/txrelayer.go
  types/transaction.go
  types/transaction_fork_hash.go
Labels: bug fix

#1952 Removed redundant queue length check in accountQueue.peek() function
  txpool/queue_account.go
Labels: bug fix

#1953 Fix bridge e2e tests for transferring tokens
  e2e-polybft/e2e/bridge_test.go
Labels: bug fix

#1949 Skip account balance check for eth_call
  e2e-polybft/e2e/jsonrpc_test.go
  jsonrpc/eth_blockchain_test.go
  jsonrpc/eth_endpoint.go
  jsonrpc/eth_state_test.go
  server/server.go
  state/executor.go
  state/runtime/evm/evm_fuzz_test.go
  state/runtime/evm/evm_test.go
  state/runtime/precompiled/native_transfer_test.go
  state/runtime/runtime.go
Labels: bug fix

#1890 Base Fee Configs
  blockchain/blockchain.go
  blockchain/blockchain_test.go
  chain/chain.go
  chain/params.go
  command/default.go
  command/genesis/genesis.go
  command/genesis/params.go
  command/genesis/polybft_params.go
  command/genesis/utils.go
Labels: feature

#1960 Fix IBFT E2E tests
  .github/workflows/e2e.yaml
  contracts/staking/query.go
  contracts/staking/query_test.go
  crypto/txsigner_london_test.go
  e2e/framework/helper.go
  e2e/framework/testserver.go
  e2e/ibft_test.go
  e2e/logs_test.go
  e2e/pos_test.go
  e2e/transaction_test.go
  e2e/txpool_test.go
  e2e/websocket_test.go
  state/executor.go
Labels: bug fix

#1965 Update web3_clientVersion endpoint to return a correct value
  Makefile
  consensus/ibft/signer/helper.go
  consensus/polybft/signer/private_test.go
  crypto/crypto.go
  docker/local/Dockerfile
  e2e-polybft/e2e/jsonrpc_test.go
  go.mod
  go.sum
  helper/keystore/keystore.go
  jsonrpc/dispatcher.go
  jsonrpc/web3_endpoint.go
  jsonrpc/web3_endpoint_test.go
  secrets/helper/helper.go
  versioning/versioning.go
Labels: bug fix

#1962 Relayer and Validator node types are represented as enum flags in E2E framework
  e2e-polybft/e2e/consensus_test.go
  e2e-polybft/e2e/migration_test.go
  e2e-polybft/framework/test-cluster.go
Labels: chore

#1973 Store BLS private key in hex instead of raw big int
  command/polybftsecrets/params.go
  command/polybftsecrets/params_test.go
  consensus/polybft/signer/private.go
  crypto/crypto.go
Labels: bug

#1975 Increase resource usage in nighly build devnet to properly load-test
  .github/workflows/deploy.nightly.devnet.yml
  .github/workflows/loadtest.yml
  loadtest/scenarios/multiple_EOA.js
  loadtest/scenarios/multiple_ERC20.js
Labels: bug fix

#1980 Test-cluster fix
  e2e-polybft/framework/test-cluster.go
Labels: bug fix

#1931 Added option to disable structLogs for debug_trace* rpc methods.
  jsonrpc/debug_endpoint.go
  jsonrpc/debug_endpoint_test.go
  state/runtime/tracer/structtracer/tracer.go
  state/runtime/tracer/structtracer/tracer_test.go
Labels: feature

#1977 Remove executed state sync events and proofs from the store
  consensus/polybft/consensus_runtime.go
  consensus/polybft/state_store_state_sync.go
  consensus/polybft/state_sync_manager.go
  consensus/polybft/state_sync_manager_test.go
Labels: feature

#1982 Do not send checkpoint if node is syncing
  consensus/polybft/checkpoint_manager.go
  consensus/polybft/checkpoint_manager_test.go
Labels: bug fix

#1983 TxRelayer num retries as an option
  txrelayer/txrelayer.go
Labels: bug fix

#1971 Omit relayer flag for IBFT consensus
  Makefile
  docker/local/Dockerfile
  docker/local/docker-compose.yml
  docker/local/polygon-edge.sh
  scripts/cluster
Labels: bug fix

#1899 EVM-831 Implement state sync relayer without blocktracker
  command/server/config/config.go
  command/server/init.go
  command/server/params.go
  command/server/server.go
  consensus/consensus.go
  consensus/polybft/consensus_runtime.go
  consensus/polybft/consensus_runtime_test.go
  consensus/polybft/contractsapi/bindings-gen/main.go
  consensus/polybft/contractsapi/contractsapi.go
  consensus/polybft/polybft.go
  consensus/polybft/polybft_test.go
  consensus/polybft/state_store_state_sync.go
  consensus/polybft/state_store_state_sync_test.go
  consensus/polybft/state_sync_relayer.go
  consensus/polybft/state_sync_relayer_test.go
  consensus/polybft/statesyncrelayer/state_sync_relayer.go
  consensus/polybft/statesyncrelayer/state_sync_relayer_test.go
  e2e-polybft/e2e/bridge_test.go
  e2e-polybft/framework/test-cluster.go
  e2e-polybft/framework/test-server.go
  jsonrpc/throttling_test.go
  server/config.go
  server/server.go
Labels: bug fix

#1986 Added option to specify a root path for IBFT validators dir
  command/common.go
  command/genesis/genesis.go
  command/genesis/params.go
  command/genesis/polybft_params.go
  command/ibft/switch/ibft_switch.go
  command/ibft/switch/params.go
  docker/local/polygon-edge.sh
  e2e/framework/config.go
  e2e/framework/testserver.go
  scripts/cluster
  validators/helper.go
Labels: bug fix, feature

#1998 `estimateGas` fix for simple value transactions and contract creations
  e2e-polybft/e2e/jsonrpc_test.go
  jsonrpc/eth_endpoint.go
  jsonrpc/eth_state_test.go
  types/transaction.go
Labels: bug fix

#2000 Expand fallback errors in tx relayer when dynamic fee tx sending fails
  txrelayer/txrelayer.go
Labels: bug fix

#1993 EVM-864 Snapshot writing error not handled
  state/executor.go
  state/immutable-trie/copy_trie.go
  state/immutable-trie/snapshot.go
  state/immutable-trie/state.go
  state/immutable-trie/storage.go
  state/state.go
  state/testing.go
  state/txn_test.go
  tests/state_test.go
  tests/testing.go
Labels: bug fix

#1996 Add unit tests for `jsonrpc.Log` and `jsonrpc.Receipt` objects
  command/secrets/output/secrets_output.go
  jsonrpc/eth_endpoint.go
  jsonrpc/eth_endpoint_test.go
  jsonrpc/filter_manager.go
  jsonrpc/filter_manager_test.go
  jsonrpc/helper_test.go
  jsonrpc/testsuite/block-with-txn-bodies.json
  jsonrpc/testsuite/block-with-txn-full.json
  jsonrpc/testsuite/receipt-contract-deployment.json
  jsonrpc/testsuite/receipt-no-logs.json
  jsonrpc/testsuite/receipt-with-logs.json
  jsonrpc/testsuite/transaction-eip1559.json
  jsonrpc/testsuite/transaction-pending.json
  jsonrpc/testsuite/transaction-sealed.json
  jsonrpc/types.go
  jsonrpc/types_test.go
Labels: bug fix

#2013 Introduce notice about IBFT removal
  command/genesis/genesis.go
  helper/common/common.go
  server/server.go
Labels: feature

#2001 CallTracer implementation for debug endpoints
  jsonrpc/debug_endpoint.go
  state/runtime/tracer/calltracer/call_tracer.go
  state/runtime/tracer/calltracer/call_tracer_test.go
Labels: feature

#1981 Extract BLS library used in polybft to a standalone package
  bls/arithmetic.go
  bls/arithmetic_test.go
  bls/private.go
  bls/private_test.go
  bls/public.go
  bls/public_test.go
  bls/signature.go
  bls/signature_test.go
  bls/testcases/hashToPoint.json
  bls/utils.go
  bls/utils_test.go
  command/polybftsecrets/params_test.go
  command/rootchain/deploy/deploy.go
  command/rootchain/registration/register_validator.go
  consensus/polybft/checkpoint_manager.go
  consensus/polybft/checkpoint_manager_test.go
  consensus/polybft/consensus_runtime.go
  consensus/polybft/consensus_runtime_test.go
  consensus/polybft/extra.go
  consensus/polybft/extra_test.go
  consensus/polybft/fsm.go
  consensus/polybft/fsm_test.go
  consensus/polybft/hash_test.go
  consensus/polybft/helpers_test.go
  consensus/polybft/polybft.go
  consensus/polybft/polybft_test.go
  consensus/polybft/proposer_calculator_test.go
  consensus/polybft/sc_integration_test.go
  consensus/polybft/signer/utils.go
  consensus/polybft/signer/utils_test.go
  consensus/polybft/stake_manager.go
  consensus/polybft/state_store_epoch_test.go
  consensus/polybft/state_sync_manager.go
  consensus/polybft/state_sync_manager_test.go
  consensus/polybft/validator/genesis_validator.go
  consensus/polybft/validator/test_helpers.go
  consensus/polybft/validator/validator_metadata.go
  consensus/polybft/validator/validator_metadata_test.go
  consensus/polybft/validator/validator_set_delta_test.go
  consensus/polybft/wallet/account.go
  consensus/polybft/wallet/key.go
  consensus/polybft/wallet/key_test.go
  e2e/framework/testserver.go
  state/runtime/precompiled/bls_agg_sigs_verification.go
  state/runtime/precompiled/bls_agg_sigs_verification_test.go
Labels: don't merge, breaking change
