Repository 0xPolygon/polygon-edge, pull requests merged in 2023-03, with the labels that each got.

#1260 TOB-EDGE-27: RecoverPubk should validate provided hashed message
  crypto/crypto.go
  crypto/crypto_test.go
Labels: bug fix

#1257 Additional block metrics
  consensus/polybft/consensus_metrics.go
Labels: feature

#1259 ERC20 token bridging (withdrawal flow)
  command/bridge/README.md
  command/bridge/bridge.go
  command/bridge/common/bridge_erc20_params.go
  command/bridge/deposit/deposit.go
  command/bridge/deposit/deposit_erc20.go
  command/bridge/deposit/params.go
  command/bridge/deposit/result.go
  command/bridge/withdraw/exit.go
  command/bridge/withdraw/withdraw_erc20.go
  command/rootchain/initcontracts/init_contracts.go
  consensus/polybft/README.md
  consensus/polybft/checkpoint_manager.go
  consensus/polybft/checkpoint_manager_test.go
  consensus/polybft/consensus_runtime.go
  consensus/polybft/consensus_runtime_test.go
  consensus/polybft/contractsapi/bindings-gen/main.go
  consensus/polybft/contractsapi/contractsapi.go
  consensus/polybft/polybft_config.go
  consensus/polybft/sc_integration_test.go
  consensus/polybft/state_store_checkpoint.go
  consensus/polybft/state_store_checkpoint_test.go
  consensus/polybft/statesyncrelayer/state_sync_relayer.go
  e2e-polybft/bridge_test.go
  e2e-polybft/consensus_test.go
  e2e-polybft/framework/test-bridge.go
  e2e-polybft/framework/test-server.go
  e2e-polybft/helpers_test.go
Labels: feature

#1201 Loadtest
  .github/workflows/deploy.devnet.eph.yml
  .github/workflows/deploy.devnet.yml
  .github/workflows/loadtest.yml
  .github/workflows/pandoras_box.yml
  loadtest/contracts/ZexCoinERC20.json
  loadtest/contracts/ZexNFT.json
  loadtest/helpers/init.js
  loadtest/scenarios/multiple.js
  loadtest/scenarios/multiple_ERC20.js
  loadtest/scenarios/simple.js
Labels: feature

#1271 EVM-439 Custom Lint rule to check file permissions
  .golangci.yml
  consensus/ibft/fork/helper_test.go
  consensus/ibft/fork/storewrapper_test.go
  consensus/polybft/helpers_test.go
  go.mod
  go.sum
  gorules/rules.go
  gorules/rules_test.go
  gorules/testdata/rules_test_data.go
Labels: feature

#1274 fix: Update init paths
  loadtest/scenarios/multiple.js
  loadtest/scenarios/multiple_ERC20.js
Labels: hotfix

#1272 Provide multi addresses instead of p2p peer ids to the manifest file
  command/genesis/polybft_params.go
  command/genesis/utils.go
  command/polybftmanifest/manifest_init.go
  consensus/polybft/README.md
  consensus/polybft/polybft_config.go
  e2e-polybft/framework/test-cluster.go
Labels: feature

#1275 Check receipt status when deploying rootchain contracts
  command/rootchain/initcontracts/init_contracts.go
Labels: bug fix

#1278 Fix `bridge-json-rpc` flag in genesis command
  command/genesis/genesis.go
Labels: bug fix

#1280 Remove Pandora from testnet and Fail on error
  .github/workflows/deploy.testnet.yml
  .github/workflows/loadtest.yml
Labels: bug fix

#1286 Fix var name in Loadtest workflow to allow on-demand triggers
  .github/workflows/deploy.devnet.eph.yml
  .github/workflows/deploy.devnet.yml
  .github/workflows/deploy.testnet.yml
  .github/workflows/loadtest.yml
  loadtest/scenarios/multiple_EOA.js
  loadtest/scenarios/multiple_ERC20.js
Labels: bug fix, feature, hotfix

#1264 Integrate secrets manager to bridge commands and rootchain init-contracts commands
  command/bridge/README.md
  command/bridge/bridge.go
  command/bridge/common/bridge_erc20_params.go
  command/bridge/deposit/deposit_erc20.go
  command/bridge/exit/exit.go
  command/bridge/withdraw/withdraw_erc20.go
  command/polybftsecrets/params.go
  command/polybftsecrets/utils.go
  command/rootchain/README.md
  command/rootchain/helper/metadata.go
  command/rootchain/initcontracts/init_contracts.go
  command/rootchain/initcontracts/params.go
  command/sidechain/helper.go
  command/sidechain/registration/params.go
  command/sidechain/registration/register_validator.go
  command/sidechain/staking/params.go
  command/sidechain/staking/stake.go
  command/sidechain/unstaking/params.go
  command/sidechain/unstaking/unstake.go
  command/sidechain/validators/params.go
  command/sidechain/validators/validator_info.go
  command/sidechain/whitelist/params.go
  command/sidechain/whitelist/whitelist_validator.go
  command/sidechain/withdraw/params.go
  command/sidechain/withdraw/withdraw.go
  consensus/polybft/README.md
  e2e-polybft/e2e/bridge_test.go
  e2e-polybft/framework/test-bridge.go
  e2e-polybft/framework/test-server.go
Labels: feature

#1292 Increase E2E polybft timeout to 45 minutes
  Makefile
Labels: bug fix

#1293 Run polybft consensus by default
  command/default.go
  command/genesis/params.go
  consensus/polybft/README.md
  consensus/polybft/polybft.go
Labels: feature

#1287 Add rootchain ERC20 token flag
  command/rootchain/initcontracts/init_contracts.go
  command/rootchain/initcontracts/params.go
Labels: feature

#1288 Send approve transaction on each deposit
  command/bridge/deposit/deposit_erc20.go
  command/rootchain/initcontracts/init_contracts.go
Labels: bug fix

#1290 Event tracker starting block support
  command/genesis/genesis.go
  command/genesis/params.go
  command/genesis/polybft_params.go
  command/genesis/utils.go
  consensus/polybft/consensus_runtime.go
  consensus/polybft/polybft_config.go
  consensus/polybft/state_sync_manager.go
  consensus/polybft/statesyncrelayer/state_sync_relayer.go
  consensus/polybft/statesyncrelayer/state_sync_relayer_test.go
  server/server.go
  tracker/event_tracker.go
Labels: feature

#1289 TOB-EDGE-15: Some errors are not handled
  .golangci.yml
  command/bridge/deposit/deposit_erc20.go
  command/bridge/exit/exit.go
  command/bridge/withdraw/withdraw_erc20.go
  command/genesis/predeploy/params.go
  command/polybftsecrets/utils.go
  consensus/polybft/consensus_runtime.go
  consensus/polybft/proposer_calculator_test.go
  crypto/crypto.go
  e2e-polybft/e2e/bridge_test.go
  e2e-polybft/e2e/consensus_test.go
  e2e-polybft/property/property_test.go
  e2e/jsonrpc_test.go
  helper/hex/hex.go
  helper/hex/hex_test.go
  helper/keccak/keccak.go
  helper/keccak/pool.go
  merkle-tree/merkle_tree_benchmark_test.go
  server/server_metrics.go
  tracker/event_tracker_store_test.go
  txpool/txpool_test.go
  types/buildroot/buildroot_fast.go
  types/receipt.go
Labels: bug fix

#1281 Add burn contract to tests
  consensus/ibft/fork/hooks_test.go
  consensus/polybft/contractsapi/artifacts-gen/main.go
  consensus/polybft/contractsapi/gen_sc_data.go
  consensus/polybft/contractsapi/init.go
  consensus/polybft/system_state_test.go
  e2e-polybft/framework/test-cluster.go
  e2e/framework/testserver.go
  state/executor.go
  state/executor_test.go
  txpool/txpool_test.go
  types/rlp_encoding_test.go
  types/types_test.go
  validators/store/contract/contract_test.go
Labels: feature

#1282 Print output of cluster bash script to both terminal and file
  scripts/cluster
Labels: feature

#1252 EVM-483 Relayer Micro Service
  command/aarelayer/aa_relayer.go
  command/aarelayer/params.go
  command/aarelayer/params_test.go
  command/aarelayer/service/aa_config.go
  command/aarelayer/service/aa_config_test.go
  command/aarelayer/service/aa_pool.go
  command/aarelayer/service/aa_server.go
  command/aarelayer/service/aa_server_test.go
  command/aarelayer/service/aa_state.go
  command/aarelayer/service/aa_types.go
  command/aarelayer/service/aa_verification.go
  command/aarelayer/service/config/config.json
  command/helper/helper.go
  command/root/root.go
Labels: feature

#1295 Initialize rootchain config instance before deploying contracts
  command/output.go
  command/rootchain/initcontracts/init_contracts.go
  command/rootchain/initcontracts/init_contracts_test.go
Labels: hotfix

#1249 Update tx pool ordering logic according to EIP-1559
  consensus/dev/dev.go
  consensus/ibft/consensus_backend.go
  consensus/polybft/block_builder.go
  helper/common/common.go
  state/executor.go
  txpool/queue_account.go
  txpool/queue_priced.go
  txpool/queue_priced_test.go
  txpool/txpool.go
  types/encoding.go
  types/transaction.go
Labels: feature

#1261 EVM-476 Add persistence to the Relayer
  command/aarelayer/aa_relayer.go
  command/aarelayer/params.go
  command/aarelayer/params_test.go
  command/aarelayer/service/aa_pool.go
  command/aarelayer/service/aa_server.go
  command/aarelayer/service/aa_server_test.go
  command/aarelayer/service/aa_state.go
  command/aarelayer/service/aa_state_test.go
Labels: feature

#1299 Incorrect block number for epoch ending exit events
  consensus/polybft/checkpoint_manager.go
  consensus/polybft/checkpoint_manager_test.go
  consensus/polybft/consensus_runtime.go
Labels: bug fix

#1269 EVM-495 AA - Relay transactions from the pool
  command/aarelayer/aa_relayer.go
  command/aarelayer/params.go
  command/aarelayer/service/aa_config.go
  command/aarelayer/service/aa_pool.go
  command/aarelayer/service/aa_pool_test.go
  command/aarelayer/service/aa_relayer_service.go
  command/aarelayer/service/aa_relayer_service_test.go
  command/aarelayer/service/aa_server_test.go
  command/aarelayer/service/aa_tx_sender.go
  command/aarelayer/service/aa_types.go
  command/aarelayer/service/config/config.json
Labels: feature

#1307 Debug logs E2E tests
  e2e-polybft/framework/test-bridge.go
  e2e-polybft/framework/test-server.go
Labels: bug fix

#1302 Reuse chain id from manifest when creating genesis configuration
  command/genesis/genesis.go
  command/genesis/polybft_params.go
Labels: bug fix

#1314 Forbid premining validators in the genesis cmd
  command/genesis/params.go
  command/genesis/polybft_params.go
  command/genesis/utils.go
  command/polybftmanifest/manifest_init.go
  consensus/polybft/extra.go
  e2e-polybft/e2e/consensus_test.go
  e2e-polybft/framework/test-cluster.go
  e2e-polybft/property/property_test.go
  state/runtime/evm/evm_test.go
  state/runtime/precompiled/native_transfer_test.go
Labels: bug fix

#1304 EVM-440-Using-UTC-time
  command/regenesis/test_on_history.go
  consensus/dev/dev.go
  consensus/ibft/consensus_backend.go
  consensus/ibft/consensus_backend_test.go
  consensus/polybft/block_builder.go
  consensus/polybft/consensus_runtime_test.go
  consensus/polybft/fsm_test.go
  consensus/polybft/helpers_test.go
  consensus/polybft/polybft.go
  consensus/polybft/polybft_test.go
  consensus/polybft/signer/signature_test.go
  crypto/crypto_test.go
  e2e-polybft/framework/test-cluster.go
  e2e/framework/ibft.go
  gorules/rules.go
  gorules/testdata/rules_test_data.go
  jsonrpc/filter_manager.go
  jsonrpc/filter_manager_test.go
  network/gossip_test.go
  txpool/event_subscription_test.go
Labels: feature

#1319 Simplify tokens amount providing in e2e tests
  command/rootchain/initcontracts/init_contracts.go
  e2e-polybft/e2e/consensus_test.go
Labels: bug fix

#1312 Simplify state transactions function in FSM
  consensus/polybft/fsm.go
  consensus/polybft/fsm_test.go
Labels: bug fix

#1316 Integrate `NativeERC20Mintable` token contract
  command/genesis/genesis.go
  command/genesis/params.go
  command/genesis/polybft_params.go
  consensus/polybft/contracts_initializer.go
  consensus/polybft/contractsapi/artifacts-gen/main.go
  consensus/polybft/contractsapi/bindings-gen/main.go
  consensus/polybft/contractsapi/contractsapi.go
  consensus/polybft/contractsapi/gen_sc_data.go
  consensus/polybft/contractsapi/init.go
  consensus/polybft/polybft.go
  consensus/polybft/polybft_config.go
  e2e-polybft/e2e/consensus_test.go
  e2e-polybft/framework/test-cluster.go
Labels: feature

#1331 EVM-553: Enable generating of functions with same names in contracts api
  command/bridge/deposit/deposit_erc20.go
  command/bridge/exit/exit.go
  command/bridge/withdraw/withdraw_erc20.go
  command/rootchain/initcontracts/init_contracts.go
  command/sidechain/registration/register_validator.go
  consensus/polybft/checkpoint_manager.go
  consensus/polybft/checkpoint_manager_test.go
  consensus/polybft/consensus_runtime.go
  consensus/polybft/contracts_initializer.go
  consensus/polybft/contractsapi/bindings-gen/main.go
  consensus/polybft/contractsapi/contractsapi.go
  consensus/polybft/contractsapi/contractsapi_test.go
  consensus/polybft/contractsapi/helper.go
  consensus/polybft/fsm.go
  consensus/polybft/fsm_test.go
  consensus/polybft/helpers_test.go
  consensus/polybft/polybft.go
  consensus/polybft/sc_integration_test.go
  consensus/polybft/state_transaction.go
  consensus/polybft/state_transaction_test.go
  consensus/polybft/statesyncrelayer/state_sync_relayer.go
Labels: feature

#1339 Evm-533 Notifications to slack about nightly builds
  .github/workflows/build.yml
  .github/workflows/nightly.yml
Labels: feature

#1325 Update smart contracts to include validators storage fix
  command/bridge/README.md
  command/bridge/common/bridge_erc20_params.go
  command/bridge/deposit/deposit_erc20.go
  command/bridge/exit/exit.go
  command/bridge/withdraw/withdraw_erc20.go
  command/rootchain/README.md
  command/rootchain/helper/metadata.go
  command/rootchain/initcontracts/init_contracts.go
  command/rootchain/initcontracts/init_contracts_test.go
  command/rootchain/initcontracts/params.go
  consensus/polybft/contractsapi/gen_sc_data.go
  consensus/polybft/fsm.go
  consensus/polybft/polybft_config.go
  consensus/polybft/system_state.go
  consensus/polybft/validator_metadata.go
  e2e-polybft/e2e/bridge_test.go
  e2e-polybft/framework/test-bridge.go
Labels: feature, breaking change

#1336 EVM-433-TOB-EDGE-35-Lack-of-domain-separation
  consensus/polybft/checkpoint_manager_test.go
  consensus/polybft/consensus_runtime.go
  consensus/polybft/consensus_runtime_test.go
  consensus/polybft/extra_test.go
  consensus/polybft/fsm.go
  consensus/polybft/fsm_test.go
  consensus/polybft/hash_test.go
  consensus/polybft/helpers_test.go
  consensus/polybft/mocks_test.go
  consensus/polybft/polybft.go
  consensus/polybft/polybft_test.go
  consensus/polybft/sc_integration_test.go
  consensus/polybft/signer/common.go
  consensus/polybft/state_sync_manager.go
  consensus/polybft/state_sync_manager_test.go
  consensus/polybft/wallet/key.go
  consensus/polybft/wallet/key_test.go
  server/server.go
  state/runtime/precompiled/bls_agg_sigs_verification.go
  state/runtime/precompiled/bls_agg_sigs_verification_test.go
Labels: bug fix

#1345 Fix the limit for TX pool contract creation size
  state/executor.go
  txpool/txpool.go
  txpool/txpool_test.go
Labels: bug fix, hotfix

#1347 EVM-568 Increase MaxBlockBacklog for block tracker
  tracker/event_tracker.go
Labels: bug fix
