Repository 0xPolygon/polygon-edge, pull requests merged in 2023-04, with the labels that each got.

#1341 EVM-533 Nightly slack notificatinos
  .github/workflows/build.yml
  .github/workflows/e2e-polybft.yml
  .github/workflows/nightly.yml
  .github/workflows/property-polybft.yml
  .github/workflows/test.yml
  Makefile
Labels: feature

#1349 Transactions allow list
  chain/params.go
  command/genesis/genesis.go
  command/genesis/params.go
  command/genesis/polybft_params.go
  contracts/system_addresses.go
  e2e-polybft/e2e/allowlist_test.go
  e2e-polybft/framework/test-cluster.go
  server/server.go
  state/executor.go
Labels: feature

#1291 EVM-516 AA Update EVM with opcodes
  chain/params.go
  crypto/txsigner.go
  state/runtime/evm/dispatch_table.go
  state/runtime/evm/evm_test.go
  state/runtime/evm/instructions.go
  state/runtime/evm/opcodes.go
  state/runtime/evm/state.go
Labels: feature

#1353 Evm 505: fuzz tests in nightly build
  .github/workflows/fuzz-test.yml
  .github/workflows/nightly.yml
  Makefile
  go.mod
  go.sum
  scripts/fuzzAll
  state/runtime/evm/evm_fuzz_test.go
Labels: feature

#1358 Add receivers to sync state actions on sequence diagram
  docs/bridge/sequences.md
Labels: feature

#1362 Move base fee elasticity multiplier to genesis file
  blockchain/blockchain.go
  blockchain/blockchain_test.go
  chain/chain.go
  command/default.go
  command/genesis/params.go
  command/genesis/polybft_params.go
Labels: feature

#1361 EVM-554: Some events might not be received by subscriber
  blockchain/subscription.go
  blockchain/subscription_test.go
Labels: bug fix

#1364 EVM-584 Panic -> send on closed channel inside syncer
  network/gossip.go
  syncer/client.go
Labels: bug fix

#1365 Obsolete block time flag from server command
  command/genesis/params.go
  command/genesis/polybft_params.go
  command/ibft/switch/params.go
  command/server/config/config.go
  command/server/init.go
  command/server/params.go
  command/server/server.go
  consensus/ibft/fork/fork.go
  consensus/ibft/fork/fork_test.go
  consensus/polybft/consensus_runtime.go
  consensus/polybft/consensus_runtime_test.go
  consensus/polybft/polybft_config.go
  consensus/polybft/sc_integration_test.go
  e2e/framework/testserver.go
  e2e/ibft_test.go
  helper/common/common.go
  helper/common/common_test.go
  server/config.go
  server/server.go
Labels: feature

#1360 Shorten execution time of E2E tests
  command/rootchain/fund/fund.go
  consensus/polybft/README.md
  consensus/polybft/contractsapi/bindings-gen/main.go
  consensus/polybft/contractsapi/contractsapi.go
  consensus/polybft/contractsapi/gen_sc_data.go
  e2e-polybft/e2e/allowlist_test.go
  e2e-polybft/e2e/bridge_test.go
  e2e-polybft/e2e/consensus_test.go
  e2e-polybft/e2e/helpers_test.go
  e2e-polybft/e2e/migration_test.go
  e2e-polybft/framework/test-cluster.go
Labels: feature

#1374 Eth_call override unit test lint fix
  state/executor_test.go
Labels: bug fix

#1380 Replace slack channel for nightly build messages
  .github/workflows/nightly.yml
Labels: feature

#1382 Move IBFT E2E tests to nighly builds
  .github/workflows/e2e.yaml
  .github/workflows/nightly.yml
Labels: feature

#1384 Remove validator-set-size flag from cluster script
  scripts/cluster
Labels: bug fix

#1376 "native-token-config" flag added to genesis command
  command/genesis/genesis.go
  command/genesis/params.go
  command/genesis/polybft_params.go
  consensus/polybft/contracts_initializer.go
  consensus/polybft/polybft.go
  consensus/polybft/polybft_config.go
  e2e-polybft/e2e/consensus_test.go
  e2e-polybft/framework/test-cluster.go
Labels: feature

#1379 Remove unused `Seal` field from the extra data
  consensus/polybft/extra.go
  consensus/polybft/extra_test.go
  consensus/polybft/hash_test.go
  consensus/polybft/polybft_test.go
Labels: breaking change

#1383 `eth_getBlockByHash` and `eth_getBlockByNumber` JSON RPC endpoints should omit `Committed` field
  consensus/consensus.go
  consensus/dev/dev.go
  consensus/dummy/dummy.go
  consensus/ibft/ibft.go
  consensus/polybft/extra.go
  consensus/polybft/extra_test.go
  consensus/polybft/polybft.go
  jsonrpc/eth_blockchain_test.go
  jsonrpc/eth_endpoint.go
  jsonrpc/mocks_test.go
Labels: bug fix

#1391 Append `ExtraVanity` to the beginning of the marshaled `ExtraData`
  command/genesis/polybft_params.go
  consensus/polybft/checkpoint_manager_test.go
  consensus/polybft/consensus_runtime_test.go
  consensus/polybft/extra.go
  consensus/polybft/extra_test.go
  consensus/polybft/fsm.go
  consensus/polybft/fsm_test.go
  consensus/polybft/hash_test.go
  consensus/polybft/polybft_test.go
  consensus/polybft/runtime_helpers_test.go
  consensus/polybft/validators_snapshot_test.go
Labels: feature

#1389 Remove manifest init step from network bootstrap workflow
  chain/chain.go
  chain/chain_test.go
  command/bridge/withdraw/withdraw_erc20.go
  command/genesis/genesis.go
  command/genesis/params.go
  command/genesis/polybft_params.go
  command/genesis/utils.go
  command/polybftmanifest/manifest_init.go
  command/regenesis/howtotest.md
  command/root/root.go
  command/rootchain/README.md
  command/rootchain/deploy/deploy.go
  command/rootchain/deploy/deploy_test.go
  command/rootchain/deploy/params.go
  command/rootchain/deploy/result.go
  command/rootchain/initcontracts/params.go
  command/rootchain/rootchain.go
  consensus/polybft/README.md
  consensus/polybft/consensus_runtime.go
  consensus/polybft/consensus_runtime_test.go
  consensus/polybft/extra_test.go
  consensus/polybft/polybft_config.go
  docker/local/polygon-edge.sh
  e2e-polybft/e2e/bridge_test.go
  e2e-polybft/e2e/consensus_test.go
  e2e-polybft/framework/test-bridge.go
  e2e-polybft/framework/test-cluster.go
  e2e-polybft/property/property_test.go
  scripts/cluster
  server/builtin.go
Labels: feature, breaking change

#1406 [RFC-201/205]: EVM-603-Register supernet and child chain
  command/genesis/polybft_params.go
  command/rootchain/deploy/deploy.go
  command/rootchain/deploy/deploy_test.go
  consensus/polybft/contractsapi/bindings-gen/main.go
  consensus/polybft/contractsapi/contractsapi.go
Labels: breaking change

#1403 WriteFailedReceipt removed
  consensus/ibft/consensus_backend.go
  consensus/polybft/block_builder.go
  state/executor.go
Labels: breaking change

#1408 [RFC-201/205]: EVM-606-Change stake command
  command/polybft/polybft_command.go
  command/polybftsecrets/params.go
  command/polybftsecrets/utils.go
  command/rootchain/helper/metadata.go
  command/rootchain/registration/params.go
  command/rootchain/registration/register_validator.go
  command/rootchain/rootchain.go
  command/rootchain/staking/params.go
  command/rootchain/staking/stake.go
  command/rootchain/whitelist/params.go
  command/rootchain/whitelist/whitelist_validators.go
  command/sidechain/staking/params.go
  consensus/polybft/checkpoint_manager_test.go
  consensus/polybft/contractsapi/bindings-gen/main.go
  consensus/polybft/contractsapi/contractsapi.go
  consensus/polybft/statesyncrelayer/state_sync_relayer_test.go
  txrelayer/txrelayer.go
Labels: breaking change

#1421 [RFC201/205]: EVM-613-Change validator info command
  command/polybft/polybft_command.go
  command/rootchain/helper/metadata.go
  command/rootchain/validators/params.go
  command/rootchain/validators/validator_info.go
  command/sidechain/helper.go
  command/sidechain/validators/params.go
  consensus/polybft/system_state.go
Labels: breaking change

#1422 Add precompiles for Bridge Allow/Block lists
  chain/params.go
  command/genesis/genesis.go
  command/genesis/params.go
  command/genesis/polybft_params.go
  contracts/system_addresses.go
  e2e-polybft/e2e/acls_test.go
  e2e-polybft/framework/test-cluster.go
  server/server.go
  state/executor.go
Labels: feature

#1441 Add burn contract address in the cluster script
  scripts/cluster
Labels: bug fix

#1445 [RFC-201/205]: EVM-622-Save full validator set in db
  consensus/polybft/consensus_runtime.go
  consensus/polybft/extra.go
  consensus/polybft/helpers_test.go
  consensus/polybft/stake_manager.go
  consensus/polybft/stake_manager_test.go
  consensus/polybft/state_store_stake.go
  consensus/polybft/state_store_stake_test.go
Labels: feature
