Repository 0xPolygon/polygon-edge, pull requests merged in 2023-07, with the labels that each got.

#1682 [EVM-722]: Full nodes should not send votes for commitments
  consensus/polybft/consensus_runtime.go
  consensus/polybft/consensus_runtime_test.go
  consensus/polybft/state_sync_manager.go
  consensus/polybft/state_sync_manager_test.go
  consensus/polybft/transport.go
Labels: bug fix

#1656 EVM-716 Check if the error is produced for duplicate TXs
  txpool/account.go
  txpool/event_manager.go
  txpool/event_subscription.go
  txpool/queue_account.go
  txpool/slot_gauge.go
  txpool/txpool.go
  txpool/txpool_test.go
Labels: bug fix

#1685 Ensure premining reserve account (0x0 address)
  command/genesis/params.go
  command/genesis/params_test.go
  command/genesis/polybft_params.go
Labels: bug fix

#1702 Fix TestE2E_Migration
  command/genesis/params.go
  command/genesis/params_test.go
  e2e-polybft/e2e/migration_test.go
Labels: bug fix

#1569 EVM-660 Use batch write inside blockchain.go (LevelDB/memory)
  blockchain/blockchain.go
  blockchain/blockchain_test.go
  blockchain/storage/batch_writer.go
  blockchain/storage/keyvalue.go
  blockchain/storage/leveldb/batch.go
  blockchain/storage/leveldb/leveldb.go
  blockchain/storage/leveldb/leveldb_test.go
  blockchain/storage/memory/batch.go
  blockchain/storage/memory/memory.go
  blockchain/storage/storage.go
  blockchain/storage/testing.go
  blockchain/testing.go
Labels: feature

#1652 [EVM-703]: Saving events in boltdb should have retry mechanism
  command/bridge/exit/exit.go
  consensus/polybft/checkpoint_manager.go
  consensus/polybft/checkpoint_manager_test.go
  consensus/polybft/consensus_runtime_test.go
  consensus/polybft/contractsapi/helper.go
  consensus/polybft/extra.go
  consensus/polybft/fsm.go
  consensus/polybft/fsm_test.go
  consensus/polybft/runtime_helpers.go
  consensus/polybft/sc_integration_test.go
  consensus/polybft/stake_manager.go
  consensus/polybft/stake_manager_fuzz_test.go
  consensus/polybft/stake_manager_test.go
  consensus/polybft/state.go
  consensus/polybft/state_event_getter.go
  consensus/polybft/state_event_getter_test.go
  consensus/polybft/state_store_checkpoint.go
  consensus/polybft/state_store_checkpoint_test.go
  consensus/polybft/state_sync_manager.go
  consensus/polybft/state_sync_manager_test.go
  consensus/polybft/statesyncrelayer/state_sync_relayer.go
  tracker/event_tracker.go
  tracker/event_tracker_store.go
  tracker/event_tracker_test.go
Labels: feature

#1601 EVM-687 Dial queue slots
  network/server.go
  network/slots.go
  network/slots_test.go
Labels: feature

#1708 fix eth_estimateGas panic
  jsonrpc/helper.go
Labels: bug fix

#1696 EVM-728 Gas price comparison for executable transactions in `pricedQueue`
  gasprice/feehistory.go
  gasprice/gasprice.go
  txpool/queue_priced.go
  txpool/queue_priced_test.go
  txpool/txpool.go
  txpool/txpool_test.go
  types/transaction.go
Labels: bug fix

#1707 EVM-543 Enable concurrent run of multiple dial tasks
  network/dial/dial_queue.go
  network/dial/dial_queue_test.go
  network/server.go
Labels: feature

#1720 EVM-731 Event tracker issue - upgrade ethgo
  go.mod
  go.sum
Labels: bug fix

#1718 EVM-735: Gas limit estimation is not precise
  consensus/polybft/checkpoint_manager.go
  consensus/polybft/consensus_runtime.go
  txrelayer/txrelayer.go
Labels: bug fix

#1728 [RFC-191] Add `governorAdmin` flag
  command/genesis/genesis.go
  command/genesis/params.go
  command/genesis/polybft_params.go
  consensus/polybft/polybft_config.go
Labels: feature

#1730 [RFC-191]: Add governance `proposal-quorum` flag
  command/genesis/genesis.go
  command/genesis/params.go
  command/genesis/polybft_params.go
  consensus/polybft/polybft_config.go
Labels: feature

#1723 [EVM-736]: Quorum calculation discrepancy between SC and Edge
  chain/params.go
  consensus/polybft/consensus_runtime.go
  consensus/polybft/extra.go
  consensus/polybft/extra_test.go
  consensus/polybft/fsm.go
  consensus/polybft/fsm_test.go
  consensus/polybft/polybft.go
  consensus/polybft/state_sync_manager.go
  consensus/polybft/state_sync_manager_test.go
  consensus/polybft/validator/validator_set.go
  consensus/polybft/validator/validator_set_test.go
  e2e-polybft/e2e/jsonrpc_test.go
  go.mod
  go.sum
Labels: bug fix

#1706 EVM-732 Tx hash calculation should include tx type and chainID
  blockchain/blockchain.go
  blockchain/blockchain_test.go
  blockchain/storage/keyvalue.go
  blockchain/storage/leveldb/leveldb_test.go
  blockchain/storage/testing.go
  chain/params.go
  consensus/polybft/blockchain_wrapper.go
  consensus/polybft/fsm.go
  consensus/polybft/fsm_test.go
  consensus/polybft/polybft.go
  consensus/polybft/state_sync_manager_test.go
  consensus/utils.go
  contracts/staking/query_test.go
  forkmanager/fork.go
  forkmanager/fork_manager.go
  forkmanager/fork_manager_test.go
  helper/keccak/keccak.go
  jsonrpc/debug_endpoint.go
  jsonrpc/debug_endpoint_test.go
  jsonrpc/eth_endpoint.go
  jsonrpc/eth_endpoint_test.go
  jsonrpc/eth_txpool_test.go
  jsonrpc/helper.go
  jsonrpc/helper_test.go
  jsonrpc/testsuite/transaction-eip1559.json
  jsonrpc/txpool_endpoint_test.go
  jsonrpc/types.go
  server/builtin.go
  server/server.go
  txpool/txpool.go
  txpool/txpool_test.go
  types/buildroot/buildroot.go
  types/rlp_encoding_test.go
  types/rlp_marshal.go
  types/rlp_unmarshal.go
  types/rlp_unmarshal_storage.go
  types/transaction.go
  types/transaction_fork_hash.go
Labels: bug fix, breaking change

#1736 EVM-707 Remove balance field from initial validators in genesis.json
  command/genesis/polybft_params.go
  command/genesis/utils.go
  command/rootchain/supernet/stakemanager/stake_manager_deploy.go
  consensus/polybft/sc_integration_test.go
  consensus/polybft/validator/genesis_validator.go
  consensus/polybft/validator/test_helpers.go
Labels: chore

#1724 EVM-720 Implement json output for all commands
  command/json_output.go
  command/rootchain/deploy/deploy.go
  command/rootchain/deploy/deploy_test.go
  command/rootchain/staking/params.go
  command/rootchain/supernet/params.go
  command/rootchain/supernet/supernet.go
  command/rootchain/validators/params.go
  command/rootchain/validators/validator_info.go
  command/rootchain/whitelist/params.go
  command/rootchain/whitelist/whitelist_validators.go
  command/rootchain/withdraw/params.go
  command/rootchain/withdraw/withdraw.go
  command/sidechain/rewards/params.go
  command/sidechain/rewards/rewards.go
  command/sidechain/unstaking/params.go
  command/sidechain/unstaking/unstake.go
  command/sidechain/withdraw/params.go
  command/sidechain/withdraw/withdraw.go
  consensus/polybft/system_state.go
Labels: bug fix

#1739 Corrected Typos in Go files
  blockchain/blockchain.go
  txpool/txpool.go
Labels: bug fix

#1741 EVM-746 Fix txpool_content and txpool_inspect for dynamic fee txs
  jsonrpc/txpool_endpoint.go
  jsonrpc/txpool_endpoint_test.go
  txpool/txpool.go
Labels: bug fix

#1744 [EVM-747]: `eth_subscribe` issue with `LogIndex`
  jsonrpc/filter_manager.go
  jsonrpc/filter_manager_test.go
Labels: bug fix

#1745 TestDiscovery_ConnectedPopulatesRoutingTable fix
  network/discovery_e2e_test.go
  network/e2e_testing.go
Labels: bug fix

#1750 Correctly initialize use allow list and use block list parameters on the access list predicates
  consensus/polybft/contracts_initializer.go
  consensus/polybft/polybft.go
  e2e-polybft/e2e/bridge_test.go
Labels: bug fix

#1747 EVM-749 Transaction pool Base Fee fix
  consensus/dev/dev.go
  consensus/ibft/consensus_backend.go
  consensus/ibft/ibft.go
  consensus/polybft/block_builder.go
  consensus/polybft/block_builder_test.go
  consensus/polybft/consensus_runtime.go
  consensus/polybft/mocks_test.go
  server/server.go
  txpool/mock_test.go
  txpool/query.go
  txpool/txpool.go
  txpool/txpool_test.go
Labels: bug fix

#1746 Implement non-native tokens bridge e2e test
  e2e-polybft/e2e/bridge_test.go
  e2e-polybft/e2e/helpers_test.go
Labels: feature

#1760 Fixing link to documentation
  docker/README.md
  scripts/README.md
Labels: documentation
