Repository 0xPolygon/polygon-edge, pull requests merged in 2023-06, with the labels that each got.

#1392 Introduce a new version of go ibft
  consensus/ibft/consensus_backend.go
  consensus/polybft/consensus_runtime.go
  consensus/polybft/consensus_runtime_test.go
  consensus/polybft/validator/validator_set.go
  go.mod
  go.sum
Labels: feature

#1576 EVM-677: Fix log index issue on `eth_getTransactionReceipt`
  jsonrpc/eth_blockchain_test.go
  jsonrpc/eth_endpoint.go
Labels: bug fix

#1571 Revise and fix cluster script when ran in docker mode
  Makefile
  command/rootchain/supernet/stakemanager/stake_manager_deploy.go
  docker/local/docker-compose.yml
  docker/local/polygon-edge.sh
  scripts/cluster
Labels: bug fix

#1544 EVM-607 Hard-forking PoC
  blockchain/blockchain.go
  blockchain/blockchain_test.go
  blockchain/testing.go
  chain/chain.go
  chain/params.go
  command/genesis/params.go
  command/genesis/polybft_params.go
  consensus/polybft/extra_test.go
  consensus/polybft/polybft.go
  forkmanager/fork.go
  forkmanager/fork_manager.go
  forkmanager/fork_manager_test.go
  server/builtin.go
  server/server.go
  tests/state_test.go
  tests/testing.go
  txpool/txpool_test.go
Labels: feature

#1581 EVM-519 Resolve slashing related TODOs in the code
  consensus/polybft/consensus_runtime.go
  consensus/polybft/fsm.go
Labels: bug fix

#1578 Prevent ACL admins to remove themselves
  e2e-polybft/e2e/acls_test.go
  e2e-polybft/e2e/bridge_test.go
  state/runtime/addresslist/addresslist.go
  state/runtime/addresslist/addresslist_test.go
Labels: feature

#1583 EVM-523 Fix race condition in gas estimation
  jsonrpc/eth_state_test.go
Labels: bug fix

#1587 Fixed error handling for op code CREATE2
  state/runtime/evm/instructions.go
  state/runtime/evm/instructions_test.go
Labels: bug fix

#1386 EVM-475 status sent, a little bit of service refactoring
  command/aarelayer/aa_relayer.go
  command/aarelayer/service/aa_relayer_service.go
  command/aarelayer/service/aa_relayer_service_test.go
  command/aarelayer/service/aa_rpc_client.go
  command/aarelayer/service/aa_state.go
  command/aarelayer/service/aa_state_test.go
  command/aarelayer/service/aa_types.go
Labels: feature

#1564 EVM-675 Implement additional metrics
  consensus/polybft/blockchain_wrapper.go
  consensus/polybft/consensus_metrics.go
  consensus/polybft/fsm.go
  jsonrpc/dispatcher.go
  jsonrpc/types.go
  network/gossip.go
  syncer/client.go
  syncer/service.go
  syncer/syncer.go
  syncer/types.go
  txpool/slot_gauge.go
  txpool/txpool.go
Labels: feature

#1589 Transaction relayer fetching gas price from current eth client instead of using hardcoded value
  command/rootchain/staking/stake.go
  command/rootchain/supernet/supernet.go
  command/rootchain/whitelist/whitelist_validators.go
  command/rootchain/withdraw/withdraw.go
  command/sidechain/helper.go
  command/sidechain/rewards/rewards.go
  command/sidechain/unstaking/unstake.go
  command/sidechain/withdraw/withdraw.go
  consensus/polybft/statesyncrelayer/state_sync_relayer.go
  e2e-polybft/e2e/jsonrpc_test.go
  e2e-polybft/e2e/migration_test.go
  e2e-polybft/framework/test-cluster.go
  e2e/framework/testserver.go
  e2e/jsonrpc_test.go
  txrelayer/txrelayer.go
Labels: bug fix

#1594 Extract reward token approve transaction to a separate function
  consensus/polybft/contracts_initializer.go
  consensus/polybft/polybft.go
  consensus/polybft/sc_integration_test.go
Labels: bug fix

#1592 Remove Prometheus metrics expiration time
  server/server_metrics.go
Labels: bug fix

#1609 TX pool debug level logging optimizations
  txpool/txpool.go
Labels: bug fix

#1612 Fix predeploy command to deploy contracts without a constructor
  helper/predeployment/predeployment.go
Labels: bug

#1607 EVM-689 The impact of database saving failures on Stake Manager func
  consensus/polybft/blockchain_wrapper.go
  consensus/polybft/consensus_runtime.go
  consensus/polybft/mocks_test.go
  consensus/polybft/stake_manager.go
  consensus/polybft/stake_manager_fuzz_test.go
  consensus/polybft/stake_manager_test.go
Labels: bug fix

#1616 Print child token address as part of deposit commands
  command/bridge/common/params.go
  command/bridge/deposit/erc1155/deposit_erc1155.go
  command/bridge/deposit/erc20/deposit_erc20.go
  command/bridge/deposit/erc721/deposit_erc721.go
  consensus/polybft/contractsapi/bindings-gen/main.go
  consensus/polybft/contractsapi/contractsapi.go
  consensus/polybft/contractsapi/gen_sc_data.go
Labels: feature

#1599 Validate commitment bridge transactions for finalized blocks
  blockchain/blockchain.go
  blockchain/testing.go
  consensus/consensus.go
  consensus/dev/dev.go
  consensus/dummy/dummy.go
  consensus/ibft/consensus_backend.go
  consensus/ibft/ibft.go
  consensus/polybft/blockchain_wrapper.go
  consensus/polybft/consensus_runtime.go
  consensus/polybft/fsm.go
  consensus/polybft/fsm_test.go
  consensus/polybft/polybft.go
  consensus/polybft/state_sync_manager.go
  consensus/polybft/state_sync_manager_test.go
Labels: bug fix

#1622 Cluster script fix for premine
  scripts/cluster
Labels: bug fix

#1626 modified the script to log message when jq is not installed
  scripts/cluster
Labels: bug fix

#1636 Bump Go version to 1.20
  .github/workflows/build.yml
  .github/workflows/e2e-polybft.yml
  .github/workflows/e2e.yaml
  .github/workflows/fuzz-test.yml
  .github/workflows/lint.yml
  .github/workflows/loadtest.yml
  .github/workflows/property-polybft.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  .golangci.yml
  docker/README.md
  docker/local/Dockerfile
  go.mod
Labels: chore

#1641 Update ethgo dependency
  go.mod
  go.sum
Labels: bug fix

#1629 [EVM-697]: Implement `eth_maxPriorityFeePerGas`
  gasprice/gasprice.go
  gasprice/gasprice_test.go
  jsonrpc/eth_endpoint.go
  server/server.go
Labels: feature

#1646 Fix cluster script for docker
  docker/local/polygon-edge.sh
Labels: bug fix

#1639 TestPoAPoSSwitch fixed
  e2e/pos_poa_switch_test.go
Labels: bug

#1645 EVM-713 Fork manager params
  chain/params.go
  chain/params_test.go
  command/genesis/params.go
  command/genesis/polybft_params.go
  consensus/polybft/polybft.go
  forkmanager/fork.go
  forkmanager/fork_manager.go
  forkmanager/fork_manager_test.go
  server/builtin.go
  server/server.go
Labels: feature

#1658 go.mod fix
  go.sum
Labels: bug fix

#1621 Ensure that the same child token addresses are calculated on both chains
  command/rootchain/deploy/deploy.go
  consensus/polybft/contracts_initializer.go
  consensus/polybft/contractsapi/gen_sc_data.go
  consensus/polybft/polybft_config.go
  e2e-polybft/e2e/bridge_test.go
  e2e-polybft/e2e/helpers_test.go
Labels: bug fix, breaking change

#1648 Deploy burn contract by default on EIP-1559 enabled
  .github/workflows/deploy.nightly.devnet.yml
  chain/params.go
  chain/params_test.go
  command/genesis/genesis.go
  command/genesis/params.go
  command/genesis/polybft_params.go
  command/genesis/utils.go
  consensus/ibft/fork/hooks_test.go
  consensus/polybft/contractsapi/artifacts-gen/main.go
  consensus/polybft/contractsapi/bindings-gen/main.go
  consensus/polybft/contractsapi/contractsapi.go
  consensus/polybft/contractsapi/gen_sc_data.go
  consensus/polybft/contractsapi/init.go
  consensus/polybft/polybft.go
  consensus/polybft/polybft_config.go
  consensus/polybft/system_state_test.go
  docker/local/polygon-edge.sh
  e2e-polybft/e2e/burn_contract_test.go
  e2e-polybft/e2e/txpool_test.go
  e2e-polybft/framework/test-cluster.go
  scripts/cluster
  tests/state_test.go
  validators/store/contract/contract_test.go
Labels: feature

#1654 Apply trace patch for CALL trace issue
  state/runtime/tracer/structtracer/tracer.go
  state/runtime/tracer/structtracer/tracer_test.go
Labels: bug fix

#1671 Fix flaky ERC721 and ERC1155 bridge tests
  e2e-polybft/e2e/bridge_test.go
Labels: bug fix

#1675 Run single relayer in cluster script by default
  docker/local/docker-compose.yml
  scripts/cluster
Labels: feature

#1684 Bump libp2p
  go.mod
  go.sum
Labels: chore

#1676 Handle state sync execution failures properly
  consensus/polybft/statesyncrelayer/state_sync_relayer.go
  scripts/cluster
Labels: bug fix

#1683 Fix/evm 719
  syncer/client.go
Labels: bug fix
