Repository 0xPolygon/polygon-edge, pull requests merged in 2023-08, with the labels that each got.

#1766 Change chainID to chainId
  docker/local/polygon-edge.sh
  jsonrpc/types.go
Labels: bug fix

#1768 [EVM-757]: Some commands did not print out errors returned by tx relayer
  command/bridge/deposit/erc1155/deposit_erc1155.go
  command/bridge/deposit/erc20/deposit_erc20.go
  command/bridge/deposit/erc721/deposit_erc721.go
Labels: bug fix

#1769 Error kind detection bug fix
  jsonrpc/eth_endpoint.go
  state/executor.go
  txrelayer/txrelayer.go
Labels: bug fix

#1765 Move `Encode*` and `Parse*` functions from `types` to `common` package
  chain/chain.go
  command/backup/params.go
  command/bridge/deposit/erc1155/deposit_erc1155.go
  command/bridge/deposit/erc20/deposit_erc20.go
  command/bridge/deposit/erc721/deposit_erc721.go
  command/bridge/withdraw/erc1155/withdraw_erc1155.go
  command/bridge/withdraw/erc20/withdraw_erc20.go
  command/bridge/withdraw/erc721/withdraw_erc721.go
  command/genesis/utils.go
  command/ibft/switch/params.go
  command/rootchain/helper/metadata.go
  command/rootchain/supernet/supernet.go
  command/server/init.go
  command/sidechain/helper.go
  command/sidechain/rewards/rewards.go
  consensus/polybft/polybft_config.go
  consensus/polybft/validator/genesis_validator.go
  e2e-polybft/e2e/bridge_test.go
  e2e-polybft/e2e/helpers_test.go
  e2e-polybft/e2e/migration_test.go
  e2e/framework/helper.go
  e2e/framework/testserver.go
  e2e/pos_test.go
  e2e/transaction_test.go
  e2e/websocket_test.go
  helper/common/common.go
  helper/common/encoding.go
  helper/staking/staking.go
  jsonrpc/codec.go
  jsonrpc/eth_endpoint.go
  tests/testing.go
Labels: chore

#1772 Detect fork state based on the current block number
  server/server.go
  txpool/txpool.go
  txpool/txpool_test.go
Labels: bug fix

#1767 Ignore messages sent by non-validators
  consensus/polybft/blockchain_wrapper.go
  consensus/polybft/checkpoint_manager.go
  consensus/polybft/checkpoint_manager_test.go
  consensus/polybft/common/hooks_parameters.go
  consensus/polybft/consensus_runtime.go
  consensus/polybft/consensus_runtime_test.go
  consensus/polybft/mocks_test.go
  consensus/polybft/proposer_calculator.go
  consensus/polybft/slashing/double_signing_tracker.go
  consensus/polybft/slashing/double_signing_tracker_test.go
  consensus/polybft/slashing/helpers_test.go
  consensus/polybft/stake_manager.go
  consensus/polybft/stake_manager_fuzz_test.go
  consensus/polybft/stake_manager_test.go
  consensus/polybft/state_store_stake.go
  consensus/polybft/state_sync_manager.go
  consensus/polybft/state_sync_manager_test.go
  consensus/polybft/system_state.go
  consensus/polybft/validator/validator_metadata.go
Labels: feature

#1777 Update `ethgo` version
  go.mod
  go.sum
Labels: bug fix

#1756 Slashing double signing tracker
  consensus/polybft/blockchain_wrapper.go
  consensus/polybft/checkpoint_manager.go
  consensus/polybft/checkpoint_manager_test.go
  consensus/polybft/common/hooks_parameters.go
  consensus/polybft/consensus_runtime.go
  consensus/polybft/consensus_runtime_test.go
  consensus/polybft/fsm.go
  consensus/polybft/ibft_consensus.go
  consensus/polybft/mocks_test.go
  consensus/polybft/polybft.go
  consensus/polybft/proposer_calculator.go
  consensus/polybft/slashing/double_signing_tracker.go
  consensus/polybft/slashing/double_signing_tracker_test.go
  consensus/polybft/slashing/helpers_test.go
  consensus/polybft/stake_manager.go
  consensus/polybft/stake_manager_fuzz_test.go
  consensus/polybft/stake_manager_test.go
  consensus/polybft/state_store_stake.go
  consensus/polybft/state_sync_manager.go
  consensus/polybft/state_sync_manager_test.go
  consensus/polybft/system_state.go
  consensus/polybft/transport.go
  consensus/polybft/validator/validator_metadata.go
  consensus/polybft/wallet/key.go
Labels: feature

#1780 polygon-edge.sh now checks if jq is installed
  docker/local/polygon-edge.sh
Labels: bug fix

#1788 [RFC-191]: EVM-760 - Utilize `ForkParams` contract
  consensus/polybft/contractsapi/bindings-gen/main.go
  consensus/polybft/contractsapi/contractsapi.go
  consensus/polybft/governance_manager.go
  consensus/polybft/governance_manager_test.go
  consensus/polybft/state_store_governance.go
  consensus/polybft/state_store_governance_test.go
Labels: feature

#1791 Use `curl` instead of `netcat` in local deployment script
  scripts/README.md
  scripts/cluster
Labels: feature

#1795 Send dynamic fee transactions to a rootchain
  command/bridge/deposit/erc1155/deposit_erc1155.go
  command/bridge/deposit/erc20/deposit_erc20.go
  command/bridge/deposit/erc721/deposit_erc721.go
  command/bridge/exit/exit.go
  command/bridge/withdraw/erc1155/withdraw_erc1155.go
  command/bridge/withdraw/erc20/withdraw_erc20.go
  command/bridge/withdraw/erc721/withdraw_erc721.go
  command/rootchain/deploy/deploy.go
  command/rootchain/fund/fund.go
  command/rootchain/helper/utils.go
  command/rootchain/registration/register_validator.go
  command/rootchain/staking/params.go
  command/rootchain/staking/stake.go
  command/rootchain/supernet/stakemanager/stake_manager_deploy.go
  command/rootchain/supernet/supernet.go
  command/rootchain/whitelist/whitelist_validators.go
  command/rootchain/withdraw/withdraw.go
  command/sidechain/rewards/rewards.go
  command/sidechain/withdraw/withdraw.go
  consensus/polybft/checkpoint_manager.go
  crypto/txsigner.go
  go.mod
  go.sum
  txpool/txpool.go
  txpool/txpool_test.go
  txrelayer/txrelayer.go
  types/types.go
Labels: bug fix

#1814 Rename checkpoint store to exit event store
  consensus/polybft/checkpoint_manager.go
  consensus/polybft/checkpoint_manager_test.go
  consensus/polybft/state.go
  consensus/polybft/state_event_getter.go
  consensus/polybft/state_store_exit_event.go
  consensus/polybft/state_store_exit_event_test.go
Labels: feature

#1704 EIP-2565 Implementation
  chain/params.go
  state/runtime/precompiled/base_test.go
  state/runtime/precompiled/modexp.go
  state/runtime/precompiled/modexp_test.go
Labels: don't merge, feature, breaking change

#1806 Sort rounds and senders in double signing tracker storage
  consensus/polybft/slashing/double_signing_tracker.go
  consensus/polybft/slashing/double_signing_tracker_test.go
  consensus/polybft/slashing/helpers_test.go
Labels: feature

#1815 slashing state transaction creation and validation
  chain/params.go
  consensus/polybft/consensus_runtime.go
  consensus/polybft/consensus_runtime_test.go
  consensus/polybft/contractsapi/bindings-gen/main.go
  consensus/polybft/contractsapi/contractsapi.go
  consensus/polybft/contractsapi/gen_sc_data.go
  consensus/polybft/fsm.go
  consensus/polybft/fsm_test.go
  consensus/polybft/slashing/double_signing_tracker.go
  consensus/polybft/state_transaction.go
Labels: feature

#1817 EVM-778 Debug Transaction endpoint - use one structure for logs
  state/runtime/evm/state.go
  state/runtime/tracer/structtracer/tracer.go
  state/runtime/tracer/structtracer/tracer_test.go
Labels: feature

#1818 EVM-779 Debug Transaction endpoint - throttling
  command/server/config/config.go
  command/server/params.go
  command/server/server.go
  jsonrpc/debug_endpoint.go
  jsonrpc/debug_endpoint_test.go
  jsonrpc/dispatcher.go
  jsonrpc/jsonrpc.go
  jsonrpc/throttling.go
  jsonrpc/throttling_test.go
  server/config.go
  server/server.go
Labels: feature

#1822 Temporary bindings and artifacts for ValidatorSet and CustomSupernetManager contracts
  consensus/polybft/contractsapi/contractsapi.go
  consensus/polybft/contractsapi/gen_sc_data.go
  consensus/polybft/fsm.go
  consensus/polybft/fsm_test.go
  consensus/polybft/slashing/double_signing_tracker.go
Labels: feature

#1823 Expose JSON RPC function for slash exit events retrieval
  consensus/consensus.go
  consensus/polybft/checkpoint_manager.go
  consensus/polybft/checkpoint_manager_test.go
  consensus/polybft/consensus_runtime.go
  consensus/polybft/polybft.go
  consensus/polybft/state.go
  consensus/polybft/state_store_exit_event.go
  consensus/polybft/state_store_exit_event_test.go
  jsonrpc/bridge_endpoint.go
  jsonrpc/bridge_endpoint_test.go
  jsonrpc/mocks_test.go
Labels: feature

#1819 EstimateGas endpoint - nonce should be automatically set the current nonce for the account
  jsonrpc/debug_endpoint.go
  jsonrpc/debug_endpoint_test.go
  jsonrpc/eth_blockchain_test.go
  jsonrpc/eth_endpoint.go
  jsonrpc/eth_endpoint_test.go
  jsonrpc/helper.go
  jsonrpc/helper_test.go
Labels: bug fix

#1825 fixed copy method
  types/transaction.go
Labels: bug fix

#1827 GenerateSlashExitProofs unit test
  consensus/polybft/checkpoint_manager_test.go
Labels: feature

#1748 Eip 2929
  chain/params.go
  helper/predeployment/predeployment.go
  state/executor.go
  state/executor_test.go
  state/runtime/access_list.go
  state/runtime/access_list_test.go
  state/runtime/evm/evm.go
  state/runtime/evm/evm_test.go
  state/runtime/evm/instructions.go
  state/runtime/evm/instructions_test.go
  state/runtime/evm/state.go
  state/runtime/precompiled/precompiled.go
  state/runtime/runtime.go
  state/txn.go
Labels: don't merge, feature

#1821 EVM-779 Throttling with concurrency
  command/server/config/config.go
  command/server/params.go
  command/server/server.go
  jsonrpc/debug_endpoint.go
  jsonrpc/dispatcher.go
  jsonrpc/jsonrpc.go
  jsonrpc/throttling.go
  jsonrpc/throttling_test.go
  server/config.go
  server/server.go
Labels: feature

#1832 Remove executed slashing exit events from storage
  consensus/polybft/checkpoint_manager.go
  consensus/polybft/contractsapi/bindings-gen/main.go
  consensus/polybft/contractsapi/contractsapi.go
  consensus/polybft/state_store_exit_event.go
  consensus/polybft/state_store_exit_event_test.go
Labels: feature

#1842 Fix nil pointer panic in debug_traceBlockByNumber RPC endpoint
  jsonrpc/debug_endpoint.go
Labels: bug fix

#1841 UUID issue
  jsonrpc/filter_manager.go
Labels: bug fix

#1847 Fix `maxFeePerGas` compensation calculation
  txrelayer/txrelayer.go
Labels: bug fix

#1839 Evm 785: enable and disable access lists in the runtime
  chain/params.go
  command/genesis/genesis.go
  command/genesis/params.go
  command/genesis/polybft_params.go
  consensus/polybft/polybft.go
  e2e-polybft/e2e/acls_test.go
  e2e-polybft/e2e/helpers_test.go
  e2e-polybft/framework/test-cluster.go
  server/server.go
  state/executor.go
  state/runtime/addresslist/addresslist.go
  state/runtime/addresslist/addresslist_test.go
  state/runtime/addresslist/genesis.go
  state/runtime/addresslist/genesis_test.go
Labels: feature

#1848 EVM-805 TxPool assumes all transactions are Legacy when checking for re-priceaction replacement GasPrice comparison bug
  txpool/txpool.go
  txpool/txpool_test.go
Labels: bug fix

#1854 Use function signature when multiple functions are defined
  consensus/polybft/contractsapi/bindings-gen/main.go
Labels: bug fix

#1860 Bump xk6-ethereum to latest
  .github/workflows/loadtest.yml
Labels: hotfix

#1859 Double the estimated fees for dynamic fee transactions
  txrelayer/txrelayer.go
Labels: bug fix
