Repository 0xPolygon/polygon-edge, pull requests merged in 2023-09, with the labels that each got.

#1865 EVM-801 Drop tx bug for updateAccountSkipsCounts
  txpool/account.go
  txpool/mock_test.go
  txpool/txpool.go
  txpool/txpool_test.go
Labels: bug fix

#1876 fixed ibft tests
  e2e/ibft_test.go
Labels: bug fix

#1877 fixed ibft tests (#1876)
  e2e/framework/helper.go
  e2e/framework/testserver.go
  e2e/ibft_test.go
  e2e/logs_test.go
  e2e/pos_test.go
  e2e/transaction_test.go
  e2e/txpool_test.go
  e2e/websocket_test.go
Labels: bug fix

#1882 Fix nightly build script by providing governor-admin flag
  .github/workflows/deploy.nightly.devnet.yml
Labels: bug fix

#1880 Index methods by signature when there is ambiguity
  consensus/polybft/contractsapi/bindings-gen/main.go
  consensus/polybft/contractsapi/contractsapi.go
  consensus/polybft/contractsapi/gen_sc_data.go
Labels: bug fix

#1874 Level-up loadtesting capacity to be aligned with current environment
  .github/workflows/deploy.nightly.devnet.yml
  .github/workflows/loadtest.yml
  .github/workflows/manual.deploy.nightly.devnet.yml
  loadtest/scenarios/multiple_EOA.js
  loadtest/scenarios/multiple_ERC20.js
Labels: bug fix

#1884 Malicious JSON RPC request unit test
  jsonrpc/jsonrpc.go
  jsonrpc/jsonrpc_test.go
Labels: bug fix

#1906 Speed up root chain contracts deployment
  command/rootchain/deploy/deploy.go
Labels: bug fix

#1887 Introduce block tracker poll interval
  command/genesis/genesis.go
  command/genesis/params.go
  command/genesis/polybft_params.go
  command/helper/helper.go
  command/server/config/config.go
  command/server/init.go
  command/server/params.go
  command/server/server.go
  consensus/polybft/common/polybft_config.go
  consensus/polybft/consensus_runtime.go
  consensus/polybft/state_sync_manager.go
  consensus/polybft/statesyncrelayer/state_sync_relayer.go
  consensus/polybft/statesyncrelayer/state_sync_relayer_test.go
  e2e-polybft/e2e/bridge_test.go
  e2e-polybft/framework/test-cluster.go
  e2e-polybft/framework/test-server.go
  server/config.go
  server/server.go
  tracker/event_tracker.go
  tracker/event_tracker_test.go
Labels: feature

#1904 Removing tx hash fork
  blockchain/blockchain.go
  blockchain/blockchain_test.go
  blockchain/storage/keyvalue.go
  blockchain/storage/leveldb/leveldb_test.go
  blockchain/storage/testing.go
  chain/params.go
  consensus/polybft/fsm.go
  consensus/polybft/fsm_test.go
  consensus/polybft/state_sync_manager_test.go
  consensus/utils.go
  contracts/staking/query_test.go
  jsonrpc/debug_endpoint.go
  jsonrpc/debug_endpoint_test.go
  jsonrpc/eth_endpoint.go
  jsonrpc/eth_endpoint_test.go
  jsonrpc/eth_txpool_test.go
  jsonrpc/helper.go
  jsonrpc/helper_test.go
  jsonrpc/txpool_endpoint_test.go
  server/server.go
  txpool/txpool.go
  txpool/txpool_test.go
  types/buildroot/buildroot.go
  types/rlp_encoding_test.go
  types/rlp_unmarshal.go
  types/transaction.go
  types/transaction_fork_hash.go
Labels: bug fix

#1918 Run Edge as non-root in Docker
  Dockerfile.release
Labels: hotfix

#1917 Fix `eth_FeeHistory` unmarshal input params error
  jsonrpc/types.go
Labels: bug fix

#1915 Updating proposer calculator on restart
  consensus/polybft/consensus_runtime_test.go
  consensus/polybft/proposer_calculator.go
  e2e-polybft/e2e/consensus_test.go
  e2e-polybft/framework/test-cluster.go
Labels: bug fix

#1914 Make stake token address as mandatory in certain use cases
  command/rootchain/fund/params.go
  command/rootchain/fund/params_test.go
  command/rootchain/helper/utils.go
  command/rootchain/supernet/stakemanager/params.go
  command/rootchain/supernet/stakemanager/params_test.go
  command/rootchain/supernet/stakemanager/stake_manager_deploy.go
  types/types.go
Labels: bug fix

#1920 Update `TestE2E_Consensus_MintableERC20NativeToken` to send dynamic fee txs
  e2e-polybft/e2e/consensus_test.go
Labels: bug fix

#1928 EVM-843 Fix block post processing
  consensus/polybft/consensus_runtime.go
  consensus/polybft/consensus_runtime_test.go
  consensus/polybft/stake_manager.go
  consensus/polybft/stake_manager_fuzz_test.go
  consensus/polybft/stake_manager_test.go
  consensus/polybft/state_event_getter.go
Labels: bug fix

#1919 Remove WithoutBridge configuration param from e2e framework
  e2e-polybft/framework/test-cluster.go
Labels: chore

#1908 Use `ErrReplacementUnderpriced`
  txpool/slot_gauge.go
  txpool/txpool.go
  txpool/txpool_test.go
Labels: bug fix

#1936 Output dynamic fee specific fields in tx relayer
  txrelayer/txrelayer.go
Labels: bug fix

#1939 Default value of JSON RPC flag in commands
  command/bridge/common/params.go
  command/helper/helper.go
  command/rootchain/validators/params.go
  command/rootchain/withdraw/params.go
  command/sidechain/rewards/params.go
  command/sidechain/unstaking/params.go
  command/sidechain/withdraw/params.go
Labels: bug fix

#1940 Eip 2565/evm 730
  chain/params.go
  state/runtime/precompiled/base_test.go
  state/runtime/precompiled/modexp.go
  state/runtime/precompiled/modexp_test.go
Labels: feature

#1942 Eip 2929
  chain/params.go
  helper/predeployment/predeployment.go
  state/executor.go
  state/executor_test.go
  state/runtime/access_list.go
  state/runtime/access_list_test.go
  state/runtime/evm/evm.go
  state/runtime/evm/evm_test.go
  state/runtime/evm/instructions.go
  state/runtime/evm/instructions_test.go
  state/runtime/evm/state.go
  state/runtime/precompiled/precompiled.go
  state/runtime/runtime.go
  state/txn.go
Labels: feature

#1935 EVM-846 Stake manager post epoch problem
  consensus/polybft/consensus_runtime.go
  consensus/polybft/stake_manager.go
  consensus/polybft/stake_manager_fuzz_test.go
  consensus/polybft/stake_manager_test.go
  consensus/polybft/validators_snapshot.go
  consensus/polybft/validators_snapshot_test.go
  jsonrpc/throttling_test.go
Labels: bug fix

#1943 EVM-841-Fix TestE2E_Bridge_Transfers
  e2e-polybft/e2e/bridge_test.go
Labels: bug fix

#1941 EVM-850 Validator rootchain balance metrics
  command/server/config/config.go
  command/server/params.go
  command/server/server.go
  consensus/consensus.go
  consensus/polybft/checkpoint_manager.go
  consensus/polybft/checkpoint_manager_test.go
  consensus/polybft/polybft.go
  consensus/polybft/stats.go
  server/config.go
  server/server.go
Labels: feature
