Repository 0xPolygon/polygon-edge, pull requests merged in 2023-01, with the labels that each got.

#1067 Feature - State Sync manager
  consensus/polybft/consensus_runtime.go
  consensus/polybft/consensus_runtime_test.go
  consensus/polybft/polybft.go
  consensus/polybft/state.go
  consensus/polybft/state_sync_manager.go
  consensus/polybft/state_sync_manager_test.go
  consensus/polybft/state_transaction.go
  consensus/polybft/transport.go
Labels: feature

#1087 Fix gasCost field in return of debug trace
  jsonrpc/debug_endpoint.go
  jsonrpc/debug_endpoint_test.go
  state/runtime/evm/evm_test.go
  state/runtime/evm/state.go
Labels: bug fix

#1086 Delegation and undelegation e2e test
  command/sidechain/helper.go
  command/sidechain/unstaking/unstake.go
  command/sidechain/withdraw/withdraw.go
  e2e-polybft/consensus_test.go
  e2e-polybft/framework/test-server.go
Labels: feature

#1084 Register validator e2e test
  command/e2e/params.go
  command/e2e/register_validator.go
  command/sidechain/helper.go
  command/sidechain/unstaking/unstake.go
  command/sidechain/withdraw/withdraw.go
  e2e-polybft/bridge_test.go
  e2e-polybft/consensus_test.go
  e2e-polybft/framework/test-cluster.go
  e2e-polybft/framework/test-server.go
  e2e-polybft/helpers_test.go
  txrelayer/txrelayer.go
  types/encoding.go
Labels: feature

#1080 Handled go routines in event tracker
  consensus/polybft/consensus_runtime.go
  consensus/polybft/polybft.go
  consensus/polybft/polybft_test.go
  consensus/polybft/state_sync_manager.go
  consensus/polybft/statesyncrelayer/state_sync_relayer.go
  server/server.go
  tracker/event_tracker.go
  tracker/event_tracker_test.go
Labels: bug fix

#1096 Fix invalid docker compose deployment
  docker/local/docker-compose.yml
  docker/local/polygon-edge.sh
Labels: bug fix

#1083 Multiple state sync commitments per epoch
  consensus/polybft/consensus_runtime.go
  consensus/polybft/fsm.go
  consensus/polybft/state.go
  consensus/polybft/state_sync_manager.go
  consensus/polybft/state_sync_manager_test.go
  consensus/polybft/state_test.go
  e2e-polybft/bridge_test.go
  e2e-polybft/framework/test-cluster.go
Labels: feature

#1110 Return FullBlock from syncer
  archive/restore.go
  archive/restore_test.go
  blockchain/blockchain.go
  blockchain/blockchain_test.go
  consensus/dev/dev.go
  consensus/ibft/ibft.go
  consensus/polybft/consensus_runtime.go
  consensus/polybft/consensus_runtime_test.go
  consensus/polybft/fsm.go
  consensus/polybft/fsm_test.go
  consensus/polybft/mocks_test.go
  consensus/polybft/polybft.go
  syncer/syncer.go
  syncer/syncer_test.go
  syncer/types.go
Labels: bug fix

#1113 EVM-356 Update checkpoint out of fsm
  consensus/polybft/checkpoint_manager.go
  consensus/polybft/checkpoint_manager_test.go
  consensus/polybft/consensus_runtime.go
  consensus/polybft/consensus_runtime_test.go
  consensus/polybft/fsm.go
  consensus/polybft/fsm_test.go
  consensus/polybft/handlers.go
  consensus/polybft/state.go
  consensus/polybft/state_sync_manager.go
  consensus/polybft/state_sync_manager_test.go
Labels: bug fix

#1115 EVM-362 Provide ExitRootHash to fsm without need for checkpointBackend
  consensus/polybft/checkpoint_manager.go
  consensus/polybft/checkpoint_manager_test.go
  consensus/polybft/consensus_runtime.go
  consensus/polybft/consensus_runtime_test.go
  consensus/polybft/fsm.go
  consensus/polybft/fsm_test.go
  consensus/polybft/mocks_test.go
Labels: feature

#1116 Initialize `closeCh` in `stateSyncManager`
  consensus/polybft/state_sync_manager.go
  consensus/polybft/state_sync_manager_test.go
  consensus/polybft/statesyncrelayer/state_sync_relayer_test.go
Labels: bug fix

#1111 Introduce dynamic fee tx type
  blockchain/blockchain.go
  state/executor.go
  types/rlp_encoding_test.go
  types/rlp_marshal.go
  types/rlp_unmarshal.go
  types/transaction.go
  types/types.go
Labels: feature

#1118 EVM-363 Move checkpoint functions out of runtime
  consensus/polybft/checkpoint_manager.go
  consensus/polybft/checkpoint_manager_test.go
  consensus/polybft/consensus_runtime.go
  consensus/polybft/consensus_runtime_test.go
Labels: feature

#1105 Add SonarQube config
  .github/workflows/ci.yml
  .github/workflows/test.yml
  sonar-project.properties
Labels: feature

#1132 TestE2E_Bridge_L2toL1Exit to work with multiple users
  e2e-polybft/bridge_test.go
Labels: feature

#1139 Use PostBlock handler in ProposerCalculator
  consensus/polybft/consensus_runtime.go
  consensus/polybft/proposer_calculator.go
Labels: feature

#1138 Add missing cluster stop invocations in e2e tests
  e2e-polybft/bridge_test.go
  e2e-polybft/consensus_test.go
Labels: bug fix

#1145 Missing tokens for deployment workflows
  .github/workflows/deploy.devnet.eph.yml
  .github/workflows/deploy.devnet.yml
  .github/workflows/deploy.testnet.yml
Labels: hotfix

#1131 E2E Relayer
  consensus/polybft/statesyncrelayer/state_sync_relayer.go
  e2e-polybft/bridge_test.go
  e2e-polybft/consensus_test.go
  e2e-polybft/framework/test-cluster.go
  e2e-polybft/framework/test-server.go
  server/server.go
Labels: bug fix

#1104 EVM-338 & EVM-340 fix race condition on account initialization
  txpool/account.go
  txpool/txpool_test.go
Labels: bug fix

#1141 BuildProofs for missed commitments
  consensus/polybft/consensus_runtime.go
  consensus/polybft/state.go
  consensus/polybft/state_sync_manager.go
  consensus/polybft/state_sync_manager_test.go
  consensus/polybft/state_test.go
  consensus/polybft/state_transaction.go
Labels: feature

#1133 EVM-360 Invalid state root error on v0.7.1-alpha2
  consensus/polybft/block_builder.go
  consensus/polybft/blockchain_wrapper.go
  consensus/polybft/fsm.go
  consensus/polybft/fsm_test.go
  consensus/polybft/mocks_test.go
Labels: bug fix

#1140 EVM-360 E2E test for tx which contains block functions
  e2e-polybft/txpool_test.go
Labels: feature

#1144 Rely on contracts api package when dealing with ABI abstractions
  command/e2e/register_validator.go
  command/rootchain/emit/emit.go
  command/rootchain/initcontracts/init_contracts.go
  command/sidechain/helper.go
  command/sidechain/staking/stake.go
  command/sidechain/unstaking/unstake.go
  command/sidechain/withdraw/withdraw.go
  consensus/polybft/checkpoint_manager.go
  consensus/polybft/checkpoint_manager_test.go
  consensus/polybft/contracts_initializer.go
  consensus/polybft/contractsapi/gen/main.go
  consensus/polybft/contractsapi/gen_sc_data.go
  consensus/polybft/contractsapi/init.go
  consensus/polybft/polybft.go
  consensus/polybft/state.go
  consensus/polybft/state_transaction.go
  consensus/polybft/statesyncrelayer/state_sync_relayer.go
  consensus/polybft/system_state.go
  e2e-polybft/bridge_test.go
  e2e-polybft/consensus_test.go
  types/state_transaction.go
Labels: feature

#1154 Exclude core-contracts from SonarQube checks
  sonar-project.properties
Labels: hotfix

#1114 Align RLP marshaling logic according to eip-2718
  blockchain/blockchain.go
  blockchain/storage/testing.go
  state/executor.go
  types/rlp_encoding_test.go
  types/rlp_marshal.go
  types/rlp_marshal_storage.go
  types/rlp_unmarshal.go
  types/rlp_unmarshal_storage.go
  types/transaction.go
Labels: feature

#1158 EVM-360 E2E test for tx which contains block functions (#2)
  e2e-polybft/txpool_test.go
Labels: feature

#1149 EVM-353 Different voting power property based test
  e2e-polybft/consensus_test.go
  e2e-polybft/framework/test-cluster.go
  e2e-polybft/property_test.go
  go.mod
  go.sum
Labels: feature

#1165 Remove `GetNonce` function from `TxRelayer`
  txrelayer/txrelayer.go
Labels: bug fix

#1162 Expose `ValidatorInfo` struct
  command/sidechain/helper.go
  command/sidechain/validators/validator_info.go
  consensus/polybft/system_state.go
  e2e-polybft/bridge_test.go
  e2e-polybft/consensus_test.go
  e2e-polybft/helpers_test.go
Labels: feature

#1062 Feature contractsapi gen
  Makefile
  consensus/polybft/contractsapi/artifacts-gen/main.go
  consensus/polybft/contractsapi/bindings-gen/main.go
  consensus/polybft/contractsapi/contractsapi.go
  consensus/polybft/contractsapi/contractsapi_test.go
  consensus/polybft/contractsapi/decoder.go
  docker/README.md
  go.mod
  go.sum
  scripts/cluster
  types/state_transaction.go
Labels: feature

#1161 EVM-395 Implement RFC-175 BLS integration
  consensus/polybft/checkpoint_manager_test.go
  consensus/polybft/signer/common.go
  consensus/polybft/signer/hash2point.go
  consensus/polybft/signer/hash2point_test.go
  consensus/polybft/signer/private.go
  consensus/polybft/signer/private_test.go
  consensus/polybft/signer/public.go
  consensus/polybft/signer/public_test.go
  consensus/polybft/signer/signature.go
  consensus/polybft/signer/signature_test.go
  consensus/polybft/signer/testcases/hashToPoint.json
  consensus/polybft/signer/utils.go
  consensus/polybft/signer/utils_test.go
  consensus/polybft/wallet/account.go
  consensus/polybft/wallet/account_test.go
  go.mod
  go.sum
Labels: bug fix

#1171 Remove unused legacy code from tx pool
  txpool/txpool.go
Labels: feature

#1163 Introduce test smart contracts as artifacts
  consensus/polybft/checkpoint_manager_test.go
  consensus/polybft/contractsapi/init.go
  consensus/polybft/contractsapi/test-contracts/TestL1StateReceiver.json
  consensus/polybft/contractsapi/test-contracts/TestL1StateReceiver.sol
  consensus/polybft/contractsapi/test-contracts/TestWriteBlockMetadata.json
  consensus/polybft/contractsapi/test-contracts/TestWriteBlockMetadata.sol
  e2e-polybft/bridge_test.go
  e2e-polybft/txpool_test.go
Labels: feature

#1160 Checkpoint data validations
  consensus/polybft/blockchain_wrapper.go
  consensus/polybft/extra.go
  consensus/polybft/extra_test.go
  consensus/polybft/fsm.go
  consensus/polybft/fsm_test.go
  consensus/polybft/mocks_test.go
  consensus/polybft/polybft.go
  consensus/polybft/polybft_test.go
  consensus/polybft/validator_metadata.go
Labels: feature

#1065 Fix hash calculation for proposal for go-ibft's update
  consensus/ibft/consensus_backend.go
  consensus/ibft/ibft.go
  consensus/ibft/messages.go
  consensus/ibft/sign_test.go
  consensus/ibft/signer/extra.go
  consensus/ibft/signer/extra_test.go
  consensus/ibft/signer/mock_test.go
  consensus/ibft/signer/signer.go
  consensus/ibft/signer/signer_test.go
  consensus/ibft/verifier.go
  go.mod
  go.sum
Labels: bug fix
