Repository 0xPolygon/polygon-edge, pull requests merged in 2023-02, with the labels that each got.

#1166 EVM-378 Use contracts api generated stubs in client code
  command/rootchain/initcontracts/init_contracts.go
  consensus/consensus.go
  consensus/polybft/checkpoint_manager.go
  consensus/polybft/checkpoint_manager_test.go
  consensus/polybft/consensus_runtime.go
  consensus/polybft/consensus_runtime_test.go
  consensus/polybft/contractsapi/bindings-gen/main.go
  consensus/polybft/contractsapi/contractsapi.go
  consensus/polybft/contractsapi/decoder.go
  consensus/polybft/contractsapi/helper.go
  consensus/polybft/fsm.go
  consensus/polybft/fsm_test.go
  consensus/polybft/helpers_test.go
  consensus/polybft/state.go
  consensus/polybft/state_sync_manager.go
  consensus/polybft/state_sync_manager_test.go
  consensus/polybft/state_test.go
  consensus/polybft/state_transaction.go
  consensus/polybft/state_transaction_test.go
  consensus/polybft/statesyncrelayer/state_sync_relayer.go
  consensus/polybft/statesyncrelayer/state_sync_relayer_test.go
  consensus/polybft/validator_metadata.go
  contracts/state_transaction.go
  e2e-polybft/bridge_test.go
  jsonrpc/bridge_endpoint.go
  jsonrpc/mocks_test.go
  types/state_transaction.go
Labels: feature

#1164 Fix EVM-372 & EVM-373 already existing directories and files are not checked for ownership and permissions
  command/helper/helper.go
  command/rootchain/server/server.go
  command/server/export/export.go
  consensus/ibft/fork/helper.go
  consensus/polybft/polybft.go
  consensus/polybft/polybft_config.go
  e2e-polybft/framework/test-cluster.go
  e2e/framework/ibft.go
  helper/common/common.go
  helper/ipc/ipc_unix.go
  helper/keystore/keystore.go
  network/e2e_testing.go
  secrets/config.go
  secrets/local/local.go
  secrets/local/local_test.go
  server/server.go
Labels: bug fix

#1185 Adapt go-ibft implementation for polybft
  consensus/ibft/consensus_backend.go
  consensus/ibft/ibft.go
  consensus/ibft/messages.go
  consensus/ibft/sign_test.go
  consensus/ibft/signer/extra.go
  consensus/ibft/signer/extra_test.go
  consensus/ibft/signer/mock_test.go
  consensus/ibft/signer/signer.go
  consensus/ibft/signer/signer_test.go
  consensus/ibft/verifier.go
  consensus/polybft/blockchain_wrapper.go
  consensus/polybft/consensus_runtime.go
  consensus/polybft/consensus_runtime_test.go
  consensus/polybft/fsm.go
  consensus/polybft/fsm_test.go
  consensus/polybft/polybft.go
  go.mod
  go.sum
Labels: feature

#1182 [EVM-370] Added --insecure flag to both ibft and polybft
  command/cli_output.go
  command/polybftsecrets/params.go
  command/polybftsecrets/result.go
  command/secrets/init/params.go
  command/secrets/init/result.go
  command/secrets/init/secrets_init.go
  command/secrets/output/result.go
  docker/local/polygon-edge.sh
  e2e-polybft/framework/test-cluster.go
  e2e/framework/testserver.go
  scripts/cluster
Labels: feature

#1159 EVM-370 Added insecure flag for local store.
  command/secrets/init/params.go
  command/secrets/init/result.go
  command/secrets/init/secrets_init.go
  command/secrets/output/result.go
  docker/local/polygon-edge.sh
Labels: feature

#1181 EVM-375 Reject contract creation transactions with large init data
  state/executor.go
  txpool/txpool.go
  txpool/txpool_test.go
Labels: bug fix

#1186 Fix validation of state transactions
  consensus/polybft/fsm.go
  consensus/polybft/fsm_test.go
  consensus/polybft/state_transaction.go
Labels: bug fix

#1170 EVM-416 Use one struct for Exit and StateSync proofs in jsonrpc
  consensus/consensus.go
  consensus/polybft/checkpoint_manager.go
  consensus/polybft/checkpoint_manager_test.go
  consensus/polybft/consensus_runtime.go
  consensus/polybft/state.go
  consensus/polybft/state_sync_manager.go
  consensus/polybft/state_sync_manager_test.go
  consensus/polybft/state_test.go
  consensus/polybft/state_transaction.go
  consensus/polybft/state_transaction_test.go
  consensus/polybft/statesyncrelayer/state_sync_relayer.go
  consensus/polybft/statesyncrelayer/state_sync_relayer_test.go
  contracts/state_transaction.go
  e2e-polybft/bridge_test.go
  jsonrpc/bridge_endpoint.go
  jsonrpc/mocks_test.go
  types/types.go
Labels: feature

#1194 GetDelegatorReward fix
  command/sidechain/helper.go
  e2e-polybft/consensus_test.go
Labels: bug fix

#1193 Rename uptime to commit epoch
  consensus/polybft/checkpoint_manager_test.go
  consensus/polybft/consensus_runtime.go
  consensus/polybft/consensus_runtime_test.go
  consensus/polybft/fsm.go
  consensus/polybft/fsm_test.go
  consensus/polybft/helpers_test.go
  consensus/polybft/state_transaction.go
Labels: feature

#1192 Introduce burn contract address
  chain/params.go
  chain/params_test.go
  command/genesis/genesis.go
  command/genesis/params.go
  command/genesis/polybft_params.go
  command/genesis/utils.go
  e2e-polybft/framework/test-cluster.go
  e2e/framework/config.go
  e2e/framework/testserver.go
  state/executor.go
  state/runtime/runtime.go
Labels: feature

#1203 Extract SC integration tests to a separate file
  consensus/polybft/checkpoint_manager_test.go
  consensus/polybft/sc_integration_test.go
Labels: feature

#1191 EVM-453 Build proposal header's extra validators bug
  consensus/polybft/fsm.go
  consensus/polybft/fsm_test.go
  e2e-polybft/consensus_test.go
Labels: bug fix

#1178 Fix Register validator e2e test
  consensus/polybft/extra.go
  consensus/polybft/fsm.go
  consensus/polybft/polybft.go
  e2e-polybft/consensus_test.go
Labels: bug fix

#1204 Update state transition logic according to EIP-1559
  helper/common/common.go
  state/executor.go
  state/executor_test.go
Labels: feature

#1175 EVM-369 fix architecture dependent `int` type
  chain/params.go
  command/genesis/params.go
  command/genesis/polybft_params.go
  command/ibft/snapshot/ibft_snapshot.go
  command/ibft/snapshot/params.go
  command/sidechain/staking/stake.go
  consensus/polybft/statesyncrelayer/state_sync_relayer.go
  helper/common/common.go
  jsonrpc/txpool_endpoint.go
  network/identity_e2e_test.go
  network/server_identity.go
  server/system_service.go
  state/executor.go
  state/runtime/evm/bitmap.go
  state/runtime/evm/state.go
  validators/store/snapshot/snapshot.go
Labels: bug fix

#1195 EVM-387(TOB-EDGE-11) & EVM-409 (TOB-EDGE-10) Fix ValidateSignatureValues
  command/e2e/register_validator.go
  crypto/crypto.go
  crypto/crypto_test.go
  crypto/txsigner.go
  crypto/txsigner_test.go
  e2e/framework/testserver.go
  e2e/pos_test.go
  e2e/transaction_test.go
  e2e/txpool_test.go
  helper/tests/testing.go
  server/server.go
  state/runtime/precompiled/base.go
  txpool/txpool_test.go
Labels: bug fix

#1207 `Signer.Sender` does not validate whole EDCSA signature parameters
  crypto/crypto.go
  crypto/crypto_test.go
  crypto/txsigner.go
  state/runtime/precompiled/base.go
Labels: bug fix

#1205 Message is not hashed before signature verification
  consensus/polybft/consensus_runtime.go
  consensus/polybft/consensus_runtime_test.go
  consensus/polybft/wallet/key.go
  consensus/polybft/wallet/key_test.go
Labels: bug fix

#1208 Encapsulate signatures validation logic in `Extra`
  consensus/polybft/extra.go
  consensus/polybft/extra_test.go
  consensus/polybft/fsm.go
  consensus/polybft/polybft.go
Labels: feature

#1215 Validate validator set delta content
  consensus/polybft/extra.go
  consensus/polybft/extra_test.go
  consensus/polybft/fsm.go
Labels: feature

#1217 Next validator hashes don't match in register validator e2e test
  e2e-polybft/consensus_test.go
Labels: bug fix

#1214 Add unhappy path tests for verify signature
  consensus/polybft/signer/signature_test.go
Labels: feature

#1229 GitHub Actions: Remove Personal access token usage and conditionally run SonarQube
  .github/workflows/build.yml
  .github/workflows/ci.yml
  .github/workflows/test.yml
Labels: bug fix

#1226 Execute block in `fsm.Insert` if cached block is undefined or mismatch detected
  consensus/polybft/fsm.go
  consensus/polybft/fsm_test.go
Labels: bug fix

#1231 Add output flag to polybft-secrets
  command/polybftsecrets/params.go
  command/polybftsecrets/result.go
Labels: feature

#1237 Update RLP marshaling for dynamic fee tx
  types/rlp_marshal.go
  types/rlp_unmarshal.go
  types/transaction.go
Labels: bug fix, feature

#1240 Added base fee to the genesis head object
  chain/chain.go
Labels: feature

#1241 Added dynamic fees validation to tx pool and state executor
  state/executor.go
  state/executor_test.go
  txpool/query.go
  txpool/txpool.go
  txpool/txpool_test.go
Labels: feature

#1243 Pass base fee to tx pool
  consensus/dev/dev.go
  consensus/ibft/consensus_backend.go
  consensus/ibft/ibft.go
  consensus/polybft/block_builder.go
  consensus/polybft/consensus_runtime.go
  consensus/polybft/mocks_test.go
  txpool/txpool.go
  txpool/txpool_test.go
Labels: feature

#1233 Introduce signature file in validator secrets to handle validator key signature
  command/e2e/register_validator.go
  command/genesis/utils.go
  command/polybftmanifest/manifest_init.go
  command/polybftsecrets/params.go
  command/polybftsecrets/params_test.go
  command/polybftsecrets/result.go
  consensus/polybft/polybft_config.go
  consensus/polybft/polybft_test.go
  consensus/polybft/sc_integration_test.go
  network/gossip.go
  secrets/helper/helper.go
  secrets/helper/helper_test.go
  secrets/local/local.go
  secrets/secrets.go
  syncer/client.go
Labels: feature

#1248 Fix key de/serialization of BLS signatures
  command/polybftmanifest/manifest_init.go
  command/polybftsecrets/params.go
  command/polybftsecrets/params_test.go
Labels: bug fix

#1247 Use Edge embedded smart contract definitions in genesis generation
  command/genesis/polybft_params.go
  consensus/polybft/contractsapi/artifact/artifacts.go
  consensus/polybft/contractsapi/artifacts-gen/main.go
  consensus/polybft/contractsapi/gen_sc_data.go
  consensus/polybft/contractsapi/init.go
Labels: bug fix

#1234 TOB-EDGE-13 Merkle Tree bugs
  consensus/polybft/checkpoint_manager.go
  consensus/polybft/checkpoint_manager_test.go
  consensus/polybft/consensus_runtime.go
  consensus/polybft/merkle_tree.go
  consensus/polybft/merkle_tree_test.go
  consensus/polybft/sc_integration_test.go
  consensus/polybft/state_store_state_sync_test.go
  consensus/polybft/state_sync_manager.go
  consensus/polybft/state_sync_manager_test.go
  consensus/polybft/state_transaction.go
  consensus/polybft/state_transaction_test.go
  merkle-tree/README.md
  merkle-tree/merkle_tree.go
  merkle-tree/merkle_tree_benchmark_test.go
  merkle-tree/merkle_tree_test.go
Labels: bug fix
