Repository 0xPolygon/polygon-edge, pull requests merged in 2023-05, with the labels that each got.

#1457 RFC-201-205 Stake manager db fix
  consensus/polybft/stake_manager.go
  consensus/polybft/stake_manager_test.go
  consensus/polybft/state_store_checkpoint.go
  consensus/polybft/state_store_stake.go
  consensus/polybft/state_store_stake_test.go
  e2e-polybft/e2e/consensus_test.go
Labels: feature

#1464 [RFC-201/205] Event log data issue workaround fix
  consensus/polybft/consensus_runtime.go
  consensus/polybft/mocks_test.go
  consensus/polybft/stake_manager.go
  consensus/polybft/stake_manager_test.go
  consensus/polybft/system_state.go
Labels: bug fix

#1456 Integrate bridge access list contracts
  command/genesis/polybft_params.go
  consensus/polybft/contracts_initializer.go
  consensus/polybft/contractsapi/artifacts-gen/main.go
  consensus/polybft/contractsapi/bindings-gen/main.go
  consensus/polybft/contractsapi/contractsapi.go
  consensus/polybft/contractsapi/gen_sc_data.go
  consensus/polybft/contractsapi/init.go
  consensus/polybft/polybft.go
  consensus/polybft/polybft_config.go
  e2e-polybft/e2e/bridge_test.go
Labels: feature

#1468 Parallelize bootstrap rootchain CLI commands
  Makefile
  command/rootchain/deploy/deploy.go
  command/rootchain/deploy/deploy_test.go
  command/rootchain/fund/fund.go
  command/rootchain/fund/params.go
  consensus/polybft/README.md
  e2e-polybft/e2e/consensus_test.go
  e2e-polybft/framework/test-bridge.go
  e2e-polybft/framework/test-server.go
  types/types.go
Labels: feature

#1472 Provide mintable parameter as a part of native token config
  command/genesis/genesis.go
  command/genesis/params.go
  command/genesis/polybft_params.go
  consensus/polybft/polybft.go
  consensus/polybft/polybft_config.go
  e2e-polybft/e2e/consensus_test.go
  e2e-polybft/framework/test-cluster.go
Labels: feature

#1494 Explicitly notify about chain id usage
  command/genesis/genesis.go
  command/genesis/params.go
Labels: hotfix

#1498 update README for Edge v0.9.0
  README.md
Labels: documentation

#1461 Fix RLP marshal byte array and enhancements to stake manager
  consensus/polybft/consensus_runtime.go
  consensus/polybft/mocks_test.go
  consensus/polybft/stake_manager.go
  consensus/polybft/stake_manager_test.go
  consensus/polybft/system_state.go
  consensus/polybft/system_state_test.go
  go.mod
  go.sum
  helper/common/common.go
  types/rlp_encoding_test.go
  types/rlp_marshal.go
Labels: bug fix

#1502 Restore running edge in local
  scripts/cluster
Labels: bug fix

#1508 Additional header validations
  consensus/polybft/fsm.go
  consensus/polybft/fsm_test.go
  types/types.go
Labels: feature

#1507 Fix `TestProperty_DifferentVotingPower` by providing randomized stake amounts
  Makefile
  e2e-polybft/property/property_test.go
Labels: bug fix

#1474 Fix `eth_getCode` for non-empty accounts without code
  state/executor.go
  state/immutable-trie/state.go
  state/immutable-trie/state_test.go
  state/state.go
  state/testing.go
  state/txn.go
  types/types.go
Labels: bug fix

#1512 Fix Lint GH workflow
  .github/workflows/lint.yml
Labels: bug fix

#1521 Differentiate `chain-id` and `supernet-id`
  command/genesis/params.go
  command/genesis/polybft_params.go
  command/rootchain/deploy/deploy.go
  command/rootchain/deploy/deploy_test.go
  command/rootchain/staking/params.go
  command/rootchain/staking/stake.go
  command/rootchain/supernet/supernet.go
  consensus/polybft/README.md
  consensus/polybft/polybft_config.go
  e2e-polybft/e2e/bridge_test.go
  e2e-polybft/e2e/consensus_test.go
  e2e-polybft/framework/test-bridge.go
  e2e-polybft/framework/test-cluster.go
  e2e-polybft/framework/test-server.go
Labels: bug fix

#1514 De-clutter devnet/testnet deployment workflows
  .github/workflows/deploy.devnet.eph.yml
  .github/workflows/deploy.devnet.yml
  .github/workflows/deploy.testnet.yml
Labels: bug fix

#1526 Fix `lint` github workflow to trigger on every pull request
  .github/workflows/lint.yml
Labels: bug fix

#1503 Add common.RetryForever() and use for concurrent sync operations
  consensus/polybft/polybft.go
  go.mod
  go.sum
  helper/common/common.go
  helper/common/common_test.go
  server/server.go
  tracker/event_tracker.go
Labels: bug fix

#1537 EVM-525 Write load test for adding peers
  network/server_discovery.go
  network/server_identity.go
  network/server_test.go
Labels: bug fix

#1520 Add a flag to `deploy` command for stake manager address
  command/polybft/polybft_command.go
  command/rootchain/deploy/deploy.go
  command/rootchain/deploy/deploy_test.go
  command/rootchain/deploy/params.go
  command/rootchain/deploy/result.go
  command/rootchain/fund/fund.go
  command/rootchain/fund/params.go
  command/rootchain/helper/metadata.go
  command/rootchain/staking/params.go
  command/rootchain/staking/stake.go
  command/rootchain/supernet/stakemanager/params.go
  command/rootchain/supernet/stakemanager/stake_manager_deploy.go
  consensus/polybft/README.md
  consensus/polybft/polybft_config.go
  e2e-polybft/e2e/bridge_test.go
  e2e-polybft/e2e/consensus_test.go
  e2e-polybft/framework/test-bridge.go
  e2e-polybft/framework/test-cluster.go
  e2e-polybft/framework/test-server.go
Labels: feature

#1469 Introduce BASEFEE opcode
  consensus/polybft/contractsapi/test-contracts/TestWriteBlockMetadata.sol
  state/runtime/evm/dispatch_table.go
  state/runtime/evm/instructions.go
  state/runtime/evm/opcodes.go
Labels: feature

#1540 Modify rootchain command to use the provided private key to fund validators
  command/rootchain/fund/fund.go
Labels: bug fix

#1550 EVM-665 No Log Bloom
  consensus/polybft/block_builder.go
  consensus/polybft/block_builder_test.go
  types/receipt.go
Labels: bug fix

#1543 EVM-671 Fix block tracker WithBlockMaxBacklog for state_sync_relayer
  tracker/event_tracker.go
Labels: bug fix

#1509 Reject future blocks
  command/genesis/genesis.go
  command/genesis/params.go
  command/genesis/polybft_params.go
  consensus/polybft/fsm.go
  consensus/polybft/fsm_test.go
  consensus/polybft/polybft.go
  consensus/polybft/polybft_config.go
  consensus/polybft/polybft_test.go
Labels: feature

#1553 Update cluster script for new stake manager deploy flow
  scripts/cluster
Labels: bug fix

#1558 Fix `eth_getStorageAt` always returning 0
  consensus/polybft/contractsapi/test-contracts/TestSimple.json
  consensus/polybft/contractsapi/test-contracts/TestSimple.sol
  e2e-polybft/e2e/jsonrpc_test.go
  jsonrpc/eth_endpoint.go
  jsonrpc/eth_state_test.go
Labels: bug fix

#1559 Return hex encoded number in eth_getBlockTransactionCountByNumber endpoint
  jsonrpc/eth_blockchain_test.go
  jsonrpc/eth_endpoint.go
  types/encoding.go
Labels: bug fix

#1563 Fix dependabot PRs reviewers
  .github/dependabot.yml
Labels: bug fix

#1561 Restore logs output functionality in cluster script
  scripts/cluster
Labels: bug fix

#1556 Remove legacy contract deployment whitelisting mechanism
  chain/params.go
  command/root/root.go
  command/whitelist/deployment/deployment.go
  command/whitelist/deployment/params.go
  command/whitelist/deployment/result.go
  command/whitelist/show/params.go
  command/whitelist/show/result.go
  command/whitelist/show/show.go
  command/whitelist/whitelist.go
  helper/config/config.go
  server/server.go
  txpool/txpool.go
  txpool/txpool_test.go
Labels: breaking change
